### ISSUE TITLE
Leveling Up Enough To Contribute

### ISSUE THREAD

**Issue by kawikaconnell** [artf/grapesjs#104]
So after looking at the codebase, I feel puzzled, mainly because I am not too intimate with Javascript or Backbone, but I would love to contribute. I have tried learning Backbone in the past, but it was rather difficult and I switched to Vue (I picked it up really quickly). Are there any resources you would recommend to help me get to speed enough to contribute? I will be more than happy to learn whatever is needed for me to help.

**Comment by artf** [comment]
thanks @kawikaconnell for your willing to help. If you want to get more about javascript I'd recommend to check https://github.com/getify/You-Dont-Know-JS which is a really well-written resource about the language. For backbone, I think their site is the best resource, there is not so much to learn (especially to be used in grapesjs), there is just a good solid principle of how to manage your business logic (Models and Collections) and listen/update changes in your Views, the rest is just a bunch of helpers.

**Comment by chrisjsimpson** [comment]
Thumbs up to https://github.com/getify/You-Dont-Know-JS it's brilliant.

More learning programming generally really thoughtful talk:
https://youtu.be/AUYPnxv0yss enjoy! 😀

On 8 Jun 2017 8:55 p.m., "Artur Arseniev" <notifications@github.com> wrote:

thanks @kawikaconnell <https://github.com/kawikaconnell> for your willing
to help. If you want to get more about javascript I'd recommend to check
https://github.com/getify/You-Dont-Know-JS which is a really well-written
resource about the language. For backbone, I think their site is the best
resource, there is not so much to learn (especially to be used in
grapesjs), there is just a good solid principle of how to manage your
business logic (Models and Collections) and listen/update changes in your
Views, the rest is just a bunch of helpers.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/artf/grapesjs/issues/104#issuecomment-307209833>, or mute
the thread
