### ISSUE TITLE
there was nothing in assetManager 

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1252]
#1237 i am sorry.Let me describe my question again。we can not  change the background-image from the style manager before dragging the image

**Comment by ronaldaug** [comment]
Ok If I am not wrong, you are asking the **css background-image property** under the **style manager**. 
Here is where the background images are added. 

<img width="796" alt="screen shot 2018-07-02 at 10 44 20 am" src="https://user-images.githubusercontent.com/33022876/42145683-a73cf012-7de8-11e8-9302-619b65674152.png">

And grapejs demo is a static page, you can't expect the uploading functions.

Instead of trying on their official demo, you must clone grapesjs and launch your own at your device or sever. So that you can add background images via the CSS.

**Comment by ionic666** [comment]
@ronaldaug Thank you for your kind answer。but if i drag a image first,and then i can change the background-image from the style manager.
