### ISSUE TITLE
Default Component Properties

### ISSUE THREAD

**Issue by emilsedgh** [artf/grapesjs#1374]
Is there any way I can change the default properties of components?

I want almost everything to be `copyable: false, resizable: false, draggable: false` unless the loaded component specifically provides a `data-resizable=true`.

So basically I want to whitelist some components to enable these instead of blacklisting.

Is it doable?

**Comment by artf** [comment]
You can update the `default` component https://grapesjs.com/docs/modules/Components.html#update-component-type

**Comment by jereddanielson** [comment]
@artf FYI that doesn't exactly work as needed. Updating the `default` component's default properties does not take effect for already-defined components (such as built in `table`, `textnode`, et. al.) because they have _already_ extended the `default` model. Updating the `default` component would only change the default behavior for any new models that further extend the new `default` model definition.

In order to update _all_ components, including built ins, to have the desired default properties, I had to iterate over them all and update them one by one. This resulted in the desired (for me) behavior of establishing across-the-board default properties.

```javascript
// Update all component model default properties
const allComps = editor.DomComponents.componentTypes.slice();
for (let i = 0; i < allComps.length; i++) {
    const thisComp = editor.DomComponents.getType(allComps[i].id);
    editor.DomComponents.addType(allComps[i].id, {
        model: thisComp.model.extend({
            defaults: {
                ...thisComp.model.prototype.defaults,
                copyable: false,
                resizable: false,
                draggable: false,
            }
        }),
        view: thisComp.view,
    });
}
```

**Comment by artf** [comment]
@jereddanielson correct, this is how you should do to update also already defined component types. Thanks for pointing this out
