### ISSUE TITLE
about the use of setAttributes

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1385]
hi，I saved an object in the custom property。
![2018-08-27_145924](https://user-images.githubusercontent.com/36065691/44645342-e2205f00-aa09-11e8-9b70-c5db90b78320.png)
And I want to implement putting values into custom properties。
![2018-08-27_150059](https://user-images.githubusercontent.com/36065691/44645389-07ad6880-aa0a-11e8-804b-17844b300833.png)
but It will cover the previous one
![2018-08-27_150154](https://user-images.githubusercontent.com/36065691/44645441-34fa1680-aa0a-11e8-804d-0d8f0a4b5591.png)
![2018-08-27_150211](https://user-images.githubusercontent.com/36065691/44645443-375c7080-aa0a-11e8-9ad7-01024ef864bc.png)

**Comment by arthuralmeidap** [comment]
so, in the second case do you want to update the same `data-info` attribute with a new key, right?

since `data-info` has a string as a type value, first you need to get it and parse to an object.

`const dataInfoObject = JSON.parse(this.model.get('data-info'))`

after that, you can update the object with the new key

`dataInfoObject[newKey] = newValue`

and then you change it back to string and replace the attribute value for your model

`this.model.set('data-info', JSON.stringfy(dataInfoObject))`


let me know if it works

**Comment by artf** [comment]
I thinks he's just looking for [addAttributes](https://grapesjs.com/docs/api/component.html#addattributes)
