### ISSUE TITLE
Manual triggering of the asset manager rendering is required after opening the AM pop-up

### ISSUE THREAD

**Issue by neculaesei** [artf/grapesjs#1411]
# Questions

Q: Are you using the latest release (older versions are NOT supported)?
A: Yes

Q. Are you facing the bug with your local copy of GrapesJS or with the current demo?
A: Local copy, latest chrome on Linux 64bit

# The issue

When opening the asset manager via `editor.runCommand('open-assets')` it should render the list of images on its own. Right now I had to call am.render() **after** opening the asset manager pop-up to get it to work.

What could be the cause?

**Comment by artf** [comment]
The issue is that currently `open-assets` doesn't handle correctly the default `types` option (which I think, in this case, it should return all assets, even not images). I'll fix this in the next release, but for now, what I think it should be even more correctly is to ask explicitly the type of assets
```js
editor.runCommand('open-assets', { types: ['image'] });
```
