### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Immortalin** [artf/grapesjs#17]
How secure is this? I.e. Will it run the risk of code injection etc. if exposed to public on a website?

**Comment by artf** [comment]
Hi @Immortalin, nice question.
Anyway, GrapesJS is pure javascript so, from some point of view, it doesn't make sense discuss about security here. For example, it's not a problem for me, or someone else, integrate some kind of escaping function, but if your concerns are about malicous code injection it's totaly useless since anyone could disable javascript.
So all your security policy should be plugged at server-side logic and not client-side

**Comment by Immortalin** [comment]
I almost forgot that you could disable JavaScript ;)
