### ISSUE TITLE
auto select componet in RTE

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#1714]
When I add a link from RTE, it is not selected as the link component, I have to deselect the parent component that is the TEXT and select again, because this does not do it directly? I thought the advantage of RTE was that, that if I add a component from RTE the TRAIT options of that component will be shown. Not that I have to exit the TEXT again :(

**Comment by chiqui3d** [comment]
I don't know if it's the right way, but I got it this way:

```js
    const rte    = editor.RichTextEditor;
    rte.remove('link');
    rte.add('link', {
        icon: `<i class="fa fa-link"></i>`,
        attributes: {
            title: 'Link',
        },
        result: rte => {
            const anchor      = rte.selection().anchorNode;
            const nextSibling = anchor && anchor.nextSibling;
            if (nextSibling && nextSibling.nodeName === 'A') {
                rte.exec('unlink');
            } else {
                const html = `<a data-gjs-type="link" class="link selected" href="#">${rte.selection()}</a>`;
                rte.insertHTML(html);
                const selectedText      = editor.getSelected();
                const selectedTextInner = rte.el.innerHTML;
                selectedText.set('content', selectedTextInner);
                editor.select(selectedText.find('.selected'));
                editor.getSelected().removeClass('selected');
            }
        }
    });
```

**Comment by artf** [comment]
>  I thought the advantage of RTE was that, that if I add a component from RTE the TRAIT options of that component will be shown. Not that I have to exit the TEXT again :(

You're right @chiqui3d but when you're editing, the HTML text is "flat", so only when you disable the RTE the text is parsed and transformed in Components. Your solution actually works (and is ok) because of this `selectedText.set('content', selectedTextInner)` and the [listener on `content` property](https://github.com/artf/grapesjs/blob/8af686cb7fa66863c04b786ed1aa704e5406252e/src/dom_components/view/ComponentTextView.js#L17)
