### ISSUE TITLE
[Bug] problem of styling with ckeditor(4)

### ISSUE THREAD

**Issue by hpruvot** [artf/grapesjs#1754]
Hello @artf and all !

Thanks again for the amazing job !

I tried to implement ckeditor with grapesjs  and it seems to work pretty much correctly but today I found something weird. I tried to screenshot this, let me know if it's not clear...

- I select a text in white, it styles the span element, all fine.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5557762/51753990-7b3bca80-20bb-11e9-94ba-f958a0c1358b.gif)

- I save my work, I reload the page
- The white style has gone, hasn't been saved. And I can't change the color anymore (but bold works). The 
`<span style="color:#ffffff;">HELLO</span>` 
has turned into 
`<span data-gjs-type="text" data-highlightable="1" id="iiklo" class="cke_editable cke_editable_inline cke_contents_ltr cke_show_borders" contenteditable="false" spellcheck="false">HELLO</span>`

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/5557762/51754011-87278c80-20bb-11e9-840a-64d999ae0bc9.gif)

Thanks a lot

**Comment by artf** [comment]
hey @hpruvot did you setup correctly the remote storage https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage
I believe you're storing/loading the HTML instead of the JSON

**Comment by hpruvot** [comment]
Hi @artf ! I'm saving JSON though, to be able to re edit my templates after saving them, and it works just fine for the rest of my components... :/

**Comment by artf** [comment]
@hpruvot mmm I'm not sure this is the real problem, I mean, I use `avoidInlineStyle` every day and I'm not facing this issue. Moreover, soon or later, this option will be removed and the `true` behavior will be the only way to go (for a lot of reasons). 
The problem is, why your RTE content is parsed by the editor (`<span style="color:#ffffff;">HELLO</span>` should be stored as static and loaded as it is). I think the fact it works without `avoidInlineStyle`, it's just a fluke. Try to create a reproducible demo

**Comment by hpruvot** [comment]
@artf you first thought was the right one !
I still double checked my code and it turned out that someone had changed my code and was indeed loading the HTML and not the JSON anymore... ¯\_(ツ)_/¯ So sorry for this loss of time...
