### ISSUE TITLE
[BUG] Custom compoent and JS

### ISSUE THREAD

**Issue by arthuralmeidap** [artf/grapesjs#1867]
Hi @artf ,

  I'm trying to create a custom component and attach a JS to it. To give you a better example, think this component as a Slideshow component. For this component, I have some custom traits to allow the user to change some pre-defined configurations. 
  The problem is happening when I attach the Js through the `script` key while I'm adding the block. 
  The `isComponent` method is not being called for my new custom component.

  Debugging the code, I discovered when the components are being parsed, there is a validation to check if the content is a string or an array. When we have an attached Js to the component, the content will be an object. 

  Checkout PR #1866 and let me know your thoughts

**Comment by artf** [comment]
> The problem is happening when I attach the Js through the script key while I'm adding the block.
The isComponent method is not being called for my new custom component.

Hi Arthur, can you provide some code example of your case because I can't really get what is the issue. 
By looking at your PR, I don't understand why are you trying to parse the `content` property, which is used by the editor for static content (eg. as a content to be edit by RTE) and so it shouldn't be parsed
```js
editor.addComponents({
	type: 'text',
	content: `<i>Some</i> <b>static content</b> for RTE`,
});
```
