### ISSUE TITLE
How to enable functionality only for specific image component, not all

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1868]
I've enabled the fa fa-pencil icon into my image components, but I want it to be enabled only in specific image components, not all of them. How can I achieve that?

This is my code
```

domc.addType("image", {
    model: {
      initToolbar() {
        typeImage.prototype.initToolbar.apply(this, arguments);
        const tb = this.get("toolbar");
        const tbExists = tb.some(item => item.command === "open-assets");

        if (!tbExists) {
          tb.unshift({
            command: "open-assets",
            label: toolbarIcon
          });
          this.set("toolbar", tb);
        }
      }
    }
  });
```

**Comment by arthuralmeidap** [comment]
You are on the right path. Yes, you have to create a new component for that but you can't override the Image component type otherwise, as you have seen, all the images will get that.

What makes those images unique? How could you differentiate between a regular image and a specific image? That logic you will need to add to your `isComponent` fn. 

Tip: Extends your new component type from the existing Image component type.

**Comment by sakshigarg9** [comment]
@arthuralmeidap can you give me reference document for extending the prevalent image component, I'm not sure how it's to be done

**Comment by sakshigarg9** [comment]
I tried this and removed gjs-data-type="image" from the img tag where i want the functionality to be applied. But, neither does it implement the functionality on it and but also messes with the rest of component properties.

```
domc.addType("image", {
    model: defaultModel.extend({
      defaults: Object.assign({}, defaultModel.prototype.defaults, {
        initToolbar() {
          typeImage.prototype.initToolbar.apply(this, arguments);
          const tb = this.get("toolbar");
          const tbExists = tb.some(item => item.command === "open-assets");

          if (!tbExists) {
            tb.unshift({
              command: "open-assets",
              label: toolbarIcon
            });
            this.set("toolbar", tb);
          }
        }
      }),
      isComponent: function(el) {
        if (el.tagName == "IMG" && /logo.png/.test(el.src)) {
          return { type: "image", src: el.src };
        }
      }
    })
  });
```

**Comment by sakshigarg9** [comment]
solved it, change id here to 'img' and updated gjs-data-type="img" in logo div

domc.addType("img", {
    model: {
      initToolbar() {
        typeImage.prototype.initToolbar.apply(this, arguments);
        const tb = this.get("toolbar");
        const tbExists = tb.some(item => item.command === "open-assets");

        if (!tbExists) {
          tb.unshift({
            command: "open-assets",
            label: toolbarIcon
          });
          this.set("toolbar", tb);
        }
      }
    }
  });

**Comment by artf** [comment]
@sakshigarg9 to prevent messes use the new [`addType`](https://grapesjs.com/docs/modules/Components.html#improvement-over-addtype) (in your case you miss the `view` property and this breaks stuff in the old declaration) BTW I suggest to create a **new** component instead of just extending the `image` (in this way you're editing all images)
