### ISSUE TITLE
Clicking enter inside a text components many times

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#1872]
Something goes crazy when the text area extend beyond a certain point. I don't know exactly how to describe it so I'm including a screen recording.
To reproduce, go to https://grapesjs.com/demo-newsletter-editor.html, enter a text component that is close o the bottom of the viewport, go to the end of the text, and keep clicking enter. At some point it starts highlighting other components and acting all crazy.
I am only clicking enter. Nothing else. Not moving the mouse.

![GrapesEnters](https://user-images.githubusercontent.com/31323376/54064879-be667e80-41cd-11e9-8790-eed20c0e453f.gif)

**Comment by artf** [comment]
CKEditor bug (indeed the default RTE is ok), probably related to the element being in the iframe (unfortunately a lot of text editors fails by not considering this aspect)

>  At some point it starts highlighting other components and acting all crazy.
I am only clicking enter. Nothing else. Not moving the mouse.

It's just hovering components due to your mouse position (not that crazy 😂)
