### ISSUE TITLE
Get change in property float

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1904]
I'm trying to listen to the change in the 'float' property whether it was shifted to the 'left' or 'right' or 'none' in Style Manager using an event but my code doesn't seem to give the desired result.
```
  editor.on('component:styleUpdate:float', (model) => 
  { console.log('style update', editor.StyleManager.getProperty('General','float')); });
```

It gives `style update null` as the output. Desirable output would be float:right, float:left or float:none

**Comment by prashant2018** [comment]
You can use the "model" passed as a parameter to get the current property. After inspecting the model object I figured out we can get the style using **model.attributes.style** 

You should get the desired output by modifying your code snippet in the following way: 
` editor.on('component:styleUpdate:float', (model) => { 
     console.log('style update', model.attributes.style);   
}); `

**Comment by prashant2018** [comment]
@sakshigarg9 The approach I mentioned above is not working for some of the components, to be more precise what I observed is that the style property is giving empty string on the components which have a class defined.  
Your approach of using editor is correct and also works for all the components, only thing is you were using incorrect sector id "**General**" instead of "**general**". Also, you need to extract the value of float in the following way **editor.StyleManager.getProperty('general','float').attributes.value**

The below code snippet works for all the components in the grapesjs-preset-webpage as I tested them. I think it should also work on your implementation:
```
editor.on('component:styleUpdate:float', (model) => 
{ 
 console.log('style update', editor.StyleManager.getProperty('general','float').attributes.value); 
});
```
