### ISSUE TITLE
[BUG] - Not able to get content of a link block

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#2013]
Hello all,

I am using grapesjs version 0.14.52.
I am having the following issue:
When I drop a link block inside the canvas, I can use the following `linkModel.get("content")`, to get the content of the link. But once I set a new content, using `linkModel.set("content", "whatever")`, `linkModel.get("content")` starts returning an empty string value.
I am able to set and ready the attributes per example using the same get and set methods, and any other property, apart from content.
After checking the linkModel JSON, the content property has the correct value in the  beginning, but for some reason is being set to empty on `linkModel.set("content", "whatever")`; the correct content value is being assigned to `linkModel {components: [ { content: "whatever" }]}`.
I am even not being able to see the property "content" in `linkModel.changed` on set, unlike the other properties.

Is anyone else facing this issue? Any idea what is wrong here and what should I change?

Now I am setting my personal property `linkModel.set("ali-link", "whatever")`, and I am able to get it normally using `linkModel.get("ali-link")`.

Thank you

**Comment by artf** [comment]
Unfortunately, this is due to the not consistent logic in the ComponentTextView
https://github.com/artf/grapesjs/blob/3f053af969ef6a688d526d158b9df7e6aa076838/src/dom_components/view/ComponentTextView.js#L87-L114

So, if you use the built-in RTE the `content` is always moved, on change, to `components`. I understand that is not coherent but a refactor here would require probably a bit of time that I don't have
