### ISSUE TITLE
[QUESTION] How make a new component to allow laravel blade directives?

### ISSUE THREAD

**Issue by msassa** [artf/grapesjs#2076]
Hi, thanks for the nice work.

I'll like to know if there is a way to use blade directives inside the code.

I already add a new functionality to edit the source code, and work just fine.
![image](https://user-images.githubusercontent.com/570080/59308899-94af6e80-8c78-11e9-8e92-07db03ef3580.png)

But when I write something like that, the canvas show a ugly text:
![image](https://user-images.githubusercontent.com/570080/59308937-b27cd380-8c78-11e9-88bf-b9c564815b31.png)

And I like to find a way that @if don't render in the canvas.
Do you know how?
The template in the front end works just fine, but I like to hide that from the canvas.
Thanks!

**Comment by verdverm** [comment]
What would parse that syntax during rendering?

I've been looking at running react in the canvas, but we need to load react and transpile components we create. There is an in browser babel script to do something like this. Haven't got it fully working yet.

Fundamentally, what you are writing is being interpreted as text/html

**Comment by msassa** [comment]
Hi, I'm saving that code into a file, in S3.
Later, I use that files in a Laravel application.
Everything work fine, the only improvement I like to do, is:

The code is correct as source code, and it has to be saved that way.
But when I visualize that block on the canvas, I just need to see the html, not the @if (...) as well as the @endif ...
It could be marked with something special as indicating that it is surrounded by a directive bucket, but that would not be necessary.

Actually, it shows something like this:
![image](https://user-images.githubusercontent.com/570080/59392750-2689ab00-8d4f-11e9-99d5-f4c7be82c58f.png)

Ideally, I would need to show something like this:
![image](https://user-images.githubusercontent.com/570080/59392849-8ed88c80-8d4f-11e9-93e7-754e5f47e786.png)

Thanks

**Comment by verdverm** [comment]
Let me see if I follow:

- you are building an application in laravel
- you want to design visual components with 🍇
- you are creating a new custom block for code editing, where you can write things like `@if`
- if you write the code outside of 🍇, then it works
- if you write it through your custom code editing component, it does not work

Does that sound about right?

Try viewing the source of the canvas iframe, where the erroneous rendering is happening. Why should that html page render the blades syntax like you expect?

**Comment by msassa** [comment]
Hi, @verdverm, good morning.
No, I'm not explaining myself well.
- I'm building an application in Laravel
- I'm designing and modifying templates in 🍇
- I create a new plugin to edit and save the code directly, this allows me to write things like:
```
@if(config('tenant.configs.service_specials')==='true')
    <a href="/search?searchtype=services" class="text-black block mt-4 mx-2 lg:inline-block lg:mt-0">ServiceS Specials</a>
@endif
```
- This works just fine when I use the template in the front end
- The only thing is that when I see that code on the canvas, I see it as this image
![image](https://user-images.githubusercontent.com/570080/59432060-d21d1480-8dbc-11e9-985b-652665688a11.png)

and I would like to see it like this:
![image](https://user-images.githubusercontent.com/570080/59432073-d6e1c880-8dbc-11e9-8e34-bb3f0a8f5556.png)

the @if (...) and @endif should not see them on the canvas, only in the code

I hope to have explained myself well this time, if not, let me know

**Comment by verdverm** [comment]
So blades is a PHP thing, and PHP blades knows how to handle the @if and render the correct html. This happens in the backend server as I understand. Is that correct?

The canvas is created by 🍇, in an iframe. It writes the html for that iframe's content directly, as you add blocks to the canvas. How would the browser and iframe know how to understand the blades syntax? Because the html of the canvas is not being created by PHP

**Comment by msassa** [comment]
I know is a php thing, but thinking in a new grapes component, can I use the view to hide the @if, and the model to write down the @if in the final code?
Or surely I am not correctly understanding the behavior of the components

**Comment by verdverm** [comment]
yeah, this is a server vs. client side rendering issue. From what I've been able to garner, PHP Blades is server side rendering. Grapes is creating an iframe where it renders the content of components, as defined by blocks. When you drop in the code editor block, and then edit code in the canvas, that is all happening in the iframe, which is not served by Laraval, and thus the `@if...` is interpreted as vanilla html. So I don't think this will work for you as you had hoped, or more generally for server-side rendering of html.

I'm working on getting client-side render frameworks functional in the canvas. Something like React or Vue. This _may_ be possible ( I think it should be ), but requires loading the react.js framework. In general with client-side rendering, the main issue is that their syntax or ES6 in general is not understood by browsers. This is why we use Babel to transpile to javascript browsers understand. I think the way to get this working is to inject the babel.js script, and then mark scripts as type `text/babel`. We'll see how this goes... blocked by #2044. That issue is a big blocker for any fixes or progress.

**Comment by artf** [comment]
@msassa If you write the code like this, it's quite hard for the editor to understand it, but if you create a kind of custom conditional component you'll get more control over it.
Here an example of your case where the condition can also be changed via trait
https://jsfiddle.net/452fvwk6/

**Comment by msassa** [comment]
> @msassa If you write the code like this, it's quite hard for the editor to understand it, but if you create a kind of custom conditional component you'll get more control over it.
> Here an example of your case where the condition can also be changed via trait
> https://jsfiddle.net/452fvwk6/

YES !!!! this is what I'm talking about ... I knew he was not explaining well. As it is done in that component, I need the @if in the code, but it can not be seen in the canvas! it is not necessary that it be interpreted or rendered as it should be (I know it is rendered server's side), it is only code. Thank you!
