### ISSUE TITLE
[QUESTION] Splitted Custom CSS

### ISSUE THREAD

**Issue by miky9585** [artf/grapesjs#2182]
@artf hello,
I've customized just a little bit your great grapes.
Example:
I've a background with repeat-x like here:
![Schermata 2019-08-04 alle 12 06 00](https://user-images.githubusercontent.com/17646742/62422289-5a7ab000-b6b0-11e9-9e7c-0cfc7437523a.png)

But on custom CSS the result is splitted into repeat-x and repeat-y
![Schermata 2019-08-04 alle 12 02 42](https://user-images.githubusercontent.com/17646742/62422308-b0e7ee80-b6b0-11e9-802a-984bdb1f4b12.png)
How I can avoid this? tnx

**Comment by pouyamiralayi** [comment]
hi! when you specify repeat-x only, what result do you expect?

**Comment by miky9585** [comment]
If I change into CUSTOM CSS the two rows of background repeat erasing them and replacing with background-repeat: repeat-x, css composer change it for me replacing and splitting into these two lines. So I don't think that issue is on trait manager but in css composer, but I don't see any code line dedicated to splitting css code

**Comment by pouyamiralayi** [comment]
did you tried this?
`    background-repeat:repeat-x, no-repeat;
`

**Comment by artf** [comment]
This is due to your browser's CSS parser ([here](https://grapesjs.com/docs/guides/Custom-CSS-parser.html#cssom-results-are-inconsistent) we explain what is happening). 
The only solution is to use a custom CSS parser. For now, we provide [grapesjs-parser-postcss](https://github.com/artf/grapesjs-parser-postcss)
