### ISSUE TITLE
[BUG]: Can't drag component if there is some space on top/left with Mode Absolute

### ISSUE THREAD

**Issue by niisar** [artf/grapesjs#2207]
Given the following code example...

``` html
<div style="height: 100px;">
  Some Space on top or left
</div>
<div id="gjs">
  <p style="padding: 25px">
    Hesdllo World!!!</p>
</div>

```

``` js
editor.getModel().set('dmode', 'absolute');
```

Results in no ability to drag and drop elements to correct position using drag icon on the panel.

![image](https://user-images.githubusercontent.com/6368685/63374396-57b5d580-c3a7-11e9-9628-9d2943857f76.png)

See Fiddle for demonstration...

https://jsfiddle.net/niisar/zc51gtnv/

**Comment by pouyamiralayi** [comment]
this is only for the drag icon, right? the manual dragging is fine.

**Comment by niisar** [comment]
> this is only for the drag icon, right? the manual dragging is fine.
> using the drag icon, it resets the position of the element from the top as it seems.

Yes this is only for drag icon.

**Comment by artf** [comment]
Yeah the problem here is the different Event object based on the context. When you trigger the drag on the component itself the Event is in the context of the iframe (because the clicked element is in iframe) but component's buttons are outside of the iframe so the context if the Event is the original `window`.

**Comment by ramusesan** [comment]
@all same issue am facing, can anybody help !
