### ISSUE TITLE
Updating grapesjs with internal [site specific] changes

### ISSUE THREAD

**Issue by mtasic-realware** [artf/grapesjs#2293]
Hello.
Is there a way to switch to lastest grapesjs version keeping changes we made to the code for our internal use?
Changes are in most cases small and regarding tweaking css and js logic -but we need those changes [mostly requested by client].
Changes are made on unminified version on grapesjs.

I will extract all changes in a document to have it just in case. What procedure should i follow ?
Can i have those changes in some external file that will build up aside from grapesjs. Or i need to enter them manually every time new version comes up?

I'm not really familiar how grapesjs is build up to be used. Any help will be appreciated.

Thanks. Mladen

**Comment by artf** [comment]
Indeed this is what happens when you update the core library, it's hard to upgrade.

> What procedure should i follow ?

There are no specific procedures, you just need to rewrite your custom logic in the new version and hope the code isn't changed that much

My personal advice, never change the core library, [create plugins](https://grapesjs.com/docs/modules/Plugins.html)

**Comment by mtasic-realware** [comment]
Can I download source code , add changes to new js file (that will alter default component or block behaviour) and include that file in project ?

**Comment by artf** [comment]
> Aas a matter of fact - that's the way plugins are made , right ?


No, with plugins, you don't touch the code of the library so the upgrade is safer and easier
