### ISSUE TITLE
[QUESTION] All instances of custom component are being updated

### ISSUE THREAD

**Issue by trafalmejo** [artf/grapesjs#2368]
Hi,

I created a custom component for a toggle button. My problem is that once I drag and drop more than one, and then I edit any of them, all instances are being updated in terms of color, size, etc.
I am using the latest version of grapesjs

~~~~
editor.BlockManager.add('toggle', {
  label: 'Toggle',
  attributes: { class:'fa fa-toggle-on'},
  category: 'Basic',
  content: '<label class="switch"> <input type="checkbox"><span class="slider"></span></label>'
})
~~~~

All the animations and properties are in the CSS that I loaded in the editor. Any idea why this can be happening?

**Comment by pouyamiralayi** [comment]
Hi! i guess this is because your blocks posses similar classes and have selectors in common. 
in the latest version, ``avoidInlineStyle`` is true by default, so are you experiencing this on the latest version?

**Comment by artf** [comment]
The guess by @pouyamiralayi is right, this happens because of the same classes and you have to [toggle](https://github.com/artf/grapesjs/issues/863#issuecomment-544144357) them in the style manager to make stylable only the component style. BTW I'll try, soon I hope, to provide a more intuitive solution
