### ISSUE TITLE
Form new <P> tag by closing the existing <p> tag while enter is clicked 

### ISSUE THREAD

**Issue by logeshkrishna0** [artf/grapesjs#2424]
## WARNING
READ and FOLLOW next 5 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Use the GitHub Issues EXCLUSIVELY for BUGS, FEATURE REQUESTS or QUESTIONS. Prefix the title of the issue with its context, eg. `[Bug]: ....`
3. Do a quick SEARCH first, to see if someone else didn't open the same issue
4. DON'T ASK to create examples/code for you, read DOCS and APIs first, then you can post what you have tried (we'd like to see your code) and what you're unable to achieve
5. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED

## You're submitting a BUG
  1. Are you using the latest release (older versions are NOT supported)?
      1. If you're not sure, type `grapesjs.version` in console and press ENTER
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
  1. If a local copy
      1. Indicate all informations about your OS, browser and GrapesJS version.
      1. Are you able to reproduce the bug from the demo?
  1. What is the expected behavior?
  1. What happens instead?
  1. If you're able to reproduce the bug indicate all the necessary steps
  1. Attach screenshots (using KAP/LICEcap), screencasts or live demo
     1. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
     1. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

## You're submitting a FEATURE REQUEST
  1. Be sure to work on the latest version, as the feature might be already there
  1. Keep in mind that the feature should be considered valid to use for everyone, not only for your case

**Comment by logeshkrishna0** [comment]
As normal behaviour while we use ENTER key it use form <div><br></div> inside the <p> tag which is normal one.
![Screenshot from 2019-11-25 12-01-29](https://user-images.githubusercontent.com/52228872/69517726-8b426600-0f7b-11ea-909c-39754f87e68d.png)
The above image shows that......
But!!!!
here is want to get <P> tag instead of <div> tag and also the present <p> tag should be closed..


The expected scenario is "The existing <p> tag should be closed and new <p> tag should be opened"
![Screenshot from 2019-11-25 12-08-48](https://user-images.githubusercontent.com/52228872/69517991-64d0fa80-0f7c-11ea-9048-1b3d75bccfa0.png)
The above image shows the expected result

**Comment by logeshkrishna0** [comment]
@artf  could you please help me out with this

**Comment by artf** [comment]
Avoid `<div>`s in `<p>`s https://stackoverflow.com/questions/5441639/how-can-i-put-div-in-p

**Comment by logeshkrishna0** [comment]
@artf that is not the excepted solution

**Comment by logeshkrishna0** [comment]
@artf please look at the screenshot

**Comment by victorcalvo12** [comment]
@artf what he is trying to say is that when you are inside of a <p> tag and hit enter, the expected result is that it would either create a <br> or a new <p> and move the cursor into it.

The current behavior is that if you hit enter once at the end of a paragraph, it creates a div and br: 
`
<p>This is a paragraph.
    <div>
        <br>
    </div>
</p>
`

After hitting once in the middle of a paragraph:
`
<p>This is 
	<div>
	 a paragraph.
	</div>
</p>
`
After hitting enter a second time in the middle of a paragraph:
`
<p>This is 
	<div>
		<div>
		   <br>
		</div>
		<div> a paragraph.
		</div>
	</div>
</p>
`

I think this ticket should be reopened.

**Comment by victorcalvo12** [comment]
@artf 
So I did some more digging and it looks like this the browsers default behavior in any tag with the `contenteditable = true` attribute
[MDN Doc](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content#differences_in_markup_generation)

What's even more unfortunate is that when a browser receives html with this invalid syntax it tries to fix it.
So this:
```
<p>This is 
	<div>
	 a paragraph.
	</div>
</p>
```
ends up rendering like this:
```
<p>This is </p>
<div>
a paragraph.
</div>
<p></p>
```
This can have some pretty unintended consequences when it comes to styling...

I take back what I said about this specific issue needing to be reopened.

I haven't tried using the ckeditor plugin, but hopefully it produces syntactically valid html when you hit enter in a p node.

Otherwise, the project should probably use ckeditor or ideally an RTE that doesn't rely on execCommand/contenteditable OOTB.
I just read in another issue where you said you wanted to avoid relying on a outside RTE, but it seems that having a native RTE in the project is quite a monumental task.
