### ISSUE TITLE
"Call stack size exceeded"

### ISSUE THREAD

**Issue by leejunkit** [artf/grapesjs#25]
Hi! Firstly thank you for creating this amazing project. We've been trying to use it, like you mentioned, as a page builder for a CMS project that we have.

We're trying to save data to RemoteStorage, and we opted to save the components and styles in JSON format, instead of saving rendered HTML and CSS. However, the `build` code in JsonGenerator.js runs recursively until we hit a "Call stack size exceeded" error in Chrome. This is happening with the default demo site in the repository. 

Would you have any ideas how we can make this recursive operation more efficient?

**Comment by artf** [comment]
Hi @leejunkit
thanks to you for giving GrapesJS a try. To be honest I've never encountered this type of error so I'll gonna check and at least try to reproduce it. I'll let you know as I know more about it.

Anyway does it happen also with HTML/CSS export? I'm not trying to convince to use it because I would prefer JSON format too in this case but I need to know if it somehow related to JSON API

**Comment by artf** [comment]
@leejunkit updated also the demo
Thanks for reporting the bug

**Comment by leejunkit** [comment]
Thank you for fixing the bug so fast! Really appreciate it :)
