### ISSUE TITLE
BUG: Problem with adding caption element block to the canvas

### ISSUE THREAD

**Issue by ghost** [artf/grapesjs#2882]
**Version:**
0.16.18

**Are you able to reproduce the bug from the demo?**
[x ] Yes
https://jsfiddle.net/triawarman/tmcoqxhp/

**What is the expected behavior?**
When drag "caption" block to canvas, will add element `<caption>Insert text here</caption>`

**What is the current behavior?**
Adding text "Insert text here" directly to the canvas, even before drop "caption" block to the canvas.

*Describe the bug **detailed***
not adding "caption" element to the canvas

**Comment by artf** [comment]
Actually, HTML allows `<caption>` only inside `<table>`s (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) so, the parser will always convert it in a text node, indeed the real issue is not the caption but the render of the text node in grapesjs.
This will produce the same effect
```js
editor.Blocks.add('test', {
	label: 'My block',
	content: 'My text',
});
```
BTW, it should be fixed in the next release, thanks for the report

**Comment by triawarman** [comment]
hy @artf thanks for your reply.
actually after `<caption>` problem, i found another problems with table, i cant drag and drop `<tr>` to the `<table>`, and `<th> <td>` to the `<tr>`

the demo code is here:
https://jsfiddle.net/triawarman/tpnco4v6/

i found issue at https://github.com/artf/grapesjs/issues/1632 trying to add custom tollbar for table/cell, but maybe there's simple way or is this a bug too (?)
