### ISSUE TITLE
BUG: Select the initial background color doesn't work

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#2928]
Version:
0.16.18

Bug:
Select the initial background color is not working

How to reproduce it:
https://imgur.com/xqkt46E

Actually:
- Component's background does not changes.

Expected:
- Component's background should change to #000000

Thanks @artf !

**Comment by RJCAM** [comment]
@tranthanhhoa I'm not able to reproduce this bug in the [demo](https://grapesjs.com/demo.html) (same as you), it's working fine here, check this:

![bg-color](https://user-images.githubusercontent.com/49693237/88790949-19609300-d180-11ea-8f33-dac576473304.gif)

What did you do before?

**Comment by mcottret** [comment]
Hi @tranthanhhoa & @RJCAM,

The bug indeed only appears when specifically selecting a background color value of `#000000`. 

Tracking it down, it is due to the [`background-color` property's default value of `'none'`](https://github.com/artf/grapesjs/blob/dev/src/style_manager/model/PropertyFactory.js#L178) being [set as `''` by the color input](https://github.com/artf/grapesjs/blob/dev/src/domain_abstract/ui/InputColor.js#L36). It later gets converted to `#000000` by the color picker, whereas its *actual* value is `rgba(0, 0, 0, 0)` (or `transparent`).

The updated value is compared to the color picker's stored value on change, & nothing is done if they are equal (hence only failing when setting it to `#000000`).

I think this should be fixed by setting the [`background-color` property's default value](https://github.com/artf/grapesjs/blob/dev/src/style_manager/model/PropertyFactory.js#L178) to `transparent`. Which should also allow to remove [the special handling of the `none` value in the `ColorInput`](https://github.com/artf/grapesjs/blob/dev/src/domain_abstract/ui/InputColor.js#L42). 

As always, I'd be happy to open a PR if this looks good to you :).

**Comment by tranthanhhoa** [comment]
background-color property's default value to transparent worked for me. Thank you so much @mcottret !
