### ISSUE TITLE
BUG: Changing the font inside top panel is disturbing the font-awesome icons

### ISSUE THREAD

**Issue by jayeshmotwani** [artf/grapesjs#2934]
Hello, I am using Montserrat google font. Ater trying so many things, finally I was able to set the font using following way:

`.gjs-pn-buttons > span{ 
    font-family: "Montserrat", sans-serif;
}`

But when I do this, the font is changed but the font-awesome icons are not working.

Please refer the following screenshot for more details. This is how it looks after I changed the font.
![Grapesjs Font change issue](https://user-images.githubusercontent.com/27188013/89150822-1220f700-d57d-11ea-97da-21bec55737ae.PNG)

Thanks for your help.

**Comment by mcottret** [comment]
Hi @jayeshmotwani !

[Font Awesome](https://fontawesome.com/) relies on the `font-family` attribute for its icons, & since your selector also targets these icons in addition to the text, [Font Awesome](https://fontawesome.com/)'s `font-family` gets overrode by yours, which breaks its icons.

I'd recommend using a different selector that would only target the text you're interested in modifying the font of & not GJS' icons.

Cheers !

**Comment by jayeshmotwani** [comment]
@mcottret Thanks for your reply.

I fixed this by adding the label text inside a tag and given my custom font to that particular tag only, instead of entire <span> of button.

Cheers!
