### ISSUE TITLE
[Question/Bug]: The image in the cell shifts the content

### ISSUE THREAD

**Issue by mmotov** [artf/grapesjs#2948]
Hello! I Have an issue, when adding an image in cell, the neighbors cell content is 'jumping' to the  bottom.
Actually this issue not only with image, but also with video, links etc.

Here is how it looks without image:
![Screen Shot 2020-08-10 at 11 59 58 AM](https://user-images.githubusercontent.com/25824414/89766575-0b582e00-db01-11ea-99ec-8ddc5094adac.png)

And now with image:
![Screen Shot 2020-08-10 at 12 00 43 PM](https://user-images.githubusercontent.com/25824414/89766638-25920c00-db01-11ea-85b7-51d0f8a112da.png)

Any idea what it might be and how to fix it?

**Comment by Ju99ernaut** [comment]
Probably related to `display: table`, the grid system uses by default, add this to your `grapesjs.init`
```js
//...
pluginsOpts: {
        //...
	'gjs-blocks-basic': {
		flexGrid:1
	}
},
//...
```

**Comment by mmotov** [comment]
@Ju99ernaut  thanks for reply, but unfortunately it didn't help.
I managed to solve this issue by overriding default Cell component. I have added
`defaults: {
        ...defaultModel.prototype.defaults,
        //...
        style: {
          'vertical-align': 'top',
        },
      }` 
But probably I'm doing something wrong

**Comment by Ju99ernaut** [comment]
I'm able to reproduce that behavior with default grid
![img1](https://user-images.githubusercontent.com/48953676/90405937-c2761b80-e0a4-11ea-9dca-c1ebd9fd0360.png)

But when I turn on flex-grid it functions as expected
![img2](https://user-images.githubusercontent.com/48953676/90405993-d3bf2800-e0a4-11ea-9d68-1dfa5ba33a4d.png)
 
Probably have to replace all previous instances of the component that use `display: table`, but I don't think that is necessary since your solution works.
