### ISSUE TITLE
Missing icons in Block manager

### ISSUE THREAD

**Issue by jamejillagit** [artf/grapesjs#2955]
Hi,

I have started using grapesjs and for some reason some of the icons from the Block Manager are missing.

![image](https://user-images.githubusercontent.com/64067337/90017538-f966be80-dcab-11ea-9cc6-e8137c55ac25.png)

I can see that the icons displayed use font awesome, while the icons not displayed have the classes "gjs-fonts" and for example "gjs-f-b1"

When looking at the CSS, I can find these styles:

```
.gjs-fonts::before {
    display: block;
    font: normal normal normal 14px font3336;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 5em
}
``

.gjs-f-b1::before {
    content: 'Q'
}

```

Why can't I see any icons? Am I supposed to add the icons manually or what do I need to do? Not sure it is related, but I also get a missing font error that I don't know where it comes from. The path not found is project/path/fonts/main-fonts.woff?v=20

Thanks for your help

**Comment by JoshuaDeanEssium** [comment]
Any solution for this? it seems the fonts arent imported from the dist min file even though they're in the dist...

**Comment by sailor95** [comment]
Hi @jamejillagit , did you find the solution for this? I also faced the same.

**Comment by EmilIpsen** [comment]
Just in case anyone else gets this, and ends up here without an answer:

I had this issue, after downloading the raw CSS + JS files from unpkg - the exact same files worked fine when running from the CDN, but I got the same error when pointing at them locally. 

I resolved this by browsing the unpkg folders (https://unpkg.com/browse/grapesjs@0.17.25/dist/) - the grapes.js files is in the root, with two folders called "css" and "fonts". The issue with icons not loading is probably caused by not having the font files downloaded, and the CSS not pointing correctly (as the path in the CSS files are looking at a relative path).

So either get all the files and use the same folder-structure, or get the font files and edit the CSS to point at the right files.
