### ISSUE TITLE
WARNING: Plugin grapesjs-style-gradient not found

### ISSUE THREAD

**Issue by gunslingor** [artf/grapesjs#2967]
https://github.com/artf/grapesjs/issues/1156

It's actually a browser console warning not an error: "index.js?08a9:70 Plugin grapesjs-style-gradient not found"

The only difference I'm seeing in the fiddle demo posted on the above ticket is that your linking externally while I'm linking internally (and I'm using kotlin DSL):

YOU
```
<script src="https://unpkg.com/grapesjs-style-gradient
"></script>
```
ME
`script(src = "/libs/grapesjs/js/grapick.min.js") {}`

Note: Everything seems to work perfectly regardless of the warning. Just a guess, but maybe some other plugin is trying to get it, maybe presets?

P.S. I am loving the framework =)

**Comment by Ju99ernaut** [comment]
Try `script(src = "/libs/grapesjs/js/grapesjs-style-gradient.min.js") {}`, `grapick` and `grapesjs-style-gradient` are different projects, also recommend  using `grapesjs-style-bg` instead of  `grapesjs-style-gradient`

**Comment by gunslingor** [comment]
I noticed in the demo they use grapick.min.css, and style-bg.min.js in the header, but there is no grapick.min.js (which exists) or style.bg.min.css, which I find very strange; I do see now I was trying to add the plugin and pluginOpts at config time for grapesjs-style-gradient" but didn't include it in the header so I was likely using "grapesjs-style-bg" (which has no pluginsOpts in the demo for some reason) or grapick maybe. Confusing... one thing is for sure, us programmers need to take a lesson from doctors and start naming stuff in meaingful latin... ANT, another neat tool, common man, lol.

**Comment by Ju99ernaut** [comment]
Just to clarify `grapick.min.js` does exist, just that it is bundled together with `grapesjs-style-bg` or `grapesjs-style-gradient` which is why it is not included when you use either of these plugins, however we have to include `grapick.min.css` because it is not bundled in any of these plugins and is required for styling the gradient slider. Also `grapesjs-preset-webpage` and `gjs-preset-webpage` are the same plugin, the other one is just an alias.

**Comment by gunslingor** [comment]
Thanks, these bread crumbs should really help the next guy too.
