### ISSUE TITLE
XSS Vulnerability in Live Preview

### ISSUE THREAD

**Issue by rukavina** [artf/grapesjs#3082]
**Version:**
0.16.22

**Are you able to reproduce the bug from the demo?**

[ x] Yes

Steps:

* Click Import HTML
* Insert `<img src="any_image_source.gif" onload="alert(1)"/>`
* The JS will be executed

Having proper "sandbox" attribute on iframe could probably mitigate the problem.

**Comment by artf** [comment]
Well if you use GrapesJS and allow the possibility to insert custom HTML, yes, Self-XSS is possible.

Unfortunately, there are few issues that do not allow me to fix this properly
* I need to access the iframe's DOM in order to add/update inner components so, the editor won't work without `sandbox="allow-same-origin"`.
* Running JS in the editor is one of its features (Components with JS) so to make them work I'd also need `allow-scripts`
* Having `allow-same-origin` and `allow-scripts` at the same time is almost like not using `sandbox` as the iframe is able to access cookies and other web storage interfaces (eg. LocalStorage, SessionStorage, etc.) of the parent document.

The only valid solution I see, for now, is by default enabling only `sandbox="allow-same-origin"`. Which means Components with JS won't work and to enable it you should change some new option, by taking the risk of Self-XSS if you also allow custom HTML import

I've seen also solutions like this https://stackoverflow.com/a/41606174 (in this case it removes the possibility to read/write cookies) but I'm not sure how is actually reliable

Any suggestion?? 😬

**Comment by rukavina** [comment]
You are right, we thought `sandbox="allow-same-origin"` will do the job, but `allow-scripts` is also needed, and then it's like not using sandbox at all.
But, what could be helpful anyway is to provide a way for grapejs users to somehow control attributes of the iframe canvas - that way they can take the responsibility and control sandbox value or other attributes.

Thanks!

**Comment by blinkybill** [comment]
if you use content security policy http header you can get around a lot of XSS issues like this. *but* there is one issue with GrapesJS atm which is that it uses **underscore.js**, which includes a function with use of "eval" so you can't make the CSP header as secure as it should be

**Comment by assadnazar** [comment]
any update on this?

**Comment by artf** [comment]
Quick update, I've started working on this one, the first step is done [here](https://github.com/artf/grapesjs/pull/3691). I had to switch to the native DOMParser in order to avoid the execution of inline event handlers in the main context.

The next step, which is the only valid/solid solution I have found so far, is the usage of [CSP with a nonce](https://content-security-policy.com/examples/allow-inline-script/) inside iframes.
The idea is to generate a random nonce (probably with an option to be customized) and apply it to all the trusted scripts/styles, this will keep Components with JS working as expected.
About pasting custom HTML/JS inside the editor we might think about an extra `trusted` option to pass on each append.
For example, by default, when someone tries to append a custom code like that (`config.allowScripts` should be enabled, otherwise scripts are removed in the Parser):
```js
editor.getWrapper().append(`<script>console.log('malicious code');</script>`);
```
Here the component will be available in the export code (due to `allowScripts`) but won't be executed in the canvas, as it is against the CSP rule (which by default won't include `unsafe-inline`).
In case I want to allow some external inline script (eg. in [grapesjs-custom-code](https://github.com/artf/grapesjs-custom-code) we should add some checkbox to allow that), I have to use the new option:
```js
editor.getWrapper().append(`<script>console.log('trusted code');</script>`, { trusted: true });
```
In this case, the code will be executed also in the canvas.
**One important note**: with CSP enabled and without `unsafe-inline` rule, all the attribute event handlers are ALWAYS disabled. From what I know there is no way to enable event handlers safely via CSP (eg. https://stackoverflow.com/a/56400044).

What do you think? What would be the right CSP to apply by default?


Hey @blinkybill that one is ready for the next release #3558

**Comment by artf** [comment]
Update about this issue.
From https://github.com/artf/grapesjs/releases/tag/v0.18.2, by default GrapesJS HTML parser, besides removing all script tags, now it also removes all event handler attributes. This allows us to keep the Component with JS functionality but prevent any kind of external script injection. So now, something like this won't produce any execution:
```js
editor.getWrapper().append(`
 <img src="xss" onerror="alert('XSS from event attribute')">
 <script>alert('XSS from script')</script>
`);
```
In case you need to enable scripts and unsafe attributes execution (on your risk):
```js
grapesjs.init({
  // ...
  parser: {
    // Default HTML parser options
    optionsHtml: {
      allowScripts: true,
      allowUnsafeAttr: true,
    }
  }
})
```
I think this issue could be closed, as by default the XSS vulnerability is prevented at the root, but I'll still leave it open for a few days if anybody has any other security related objections.

**Comment by fredrickreuben** [comment]
events wont work example window.onload = function () {
     alert('Page has fully loaded!');
}; this deos not work
