### ISSUE TITLE
BUG: RichTextEditor is not oppening in IE11.

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3095]
When in the Canvas, I double click on some text to open the RichTextEditor in IE11, it throws me an error and does not open. In all other browsers it works. Attached a vide in the pptx and the code:
[Presentation2.pptx](https://github.com/artf/grapesjs/files/5438803/Presentation2.pptx)

        richTextEditor.add('insertHtml', {
            icon: '<select class="placeholders-select">' +
                    options()
                + '</select>',
                // Bind the 'result' on 'change' listener
            event: 'change',
            result: (rte, action) => rte.exec('insertHtml', action.btn.firstChild.value),
            update: (rte, action) => {
                const value = rte.doc.queryCommandValue(action.name)
                if (value != 'false') { // value is a string
                    action.btn.firstChild.value = value
                }
            },
        })

**Comment by fq-selbach** [comment]
I'm surprised that you could even open it in IE11 since there is so much ES6 code and heavy template usage that isn't supported at all by IE11. I'd suggest to get rid of IE11 or at least **build** your templates/pages/widgets in a modern browser. If you are lucky you will at least be able **use** them in IE11 after export.

**Comment by devuniverse** [comment]
IE ... #shivers
