### ISSUE TITLE
Does getHtml() remove the inline style property?

### ISSUE THREAD

**Issue by DodoTrip** [artf/grapesjs#3252]
I was fiddling with ways that you could change the style of elements inside the canvas and i noticed that by using the color-picker trait to set the inline style color property of the element (not the inline style tag that you get through the getCS() ), that style property was completely gone when getHtml() was used.I noticed there was a property avoidInlineStyle that was deprecated looking in the issues. If so why is that the behaviour and why isn't this an option anymore? I would like to save my css where specifically needed inlined and not have an extra style tag and all these unique ids bloating the html as i am not utilizing the style manager. Is this in any way feasible?

**Comment by artf** [comment]
Hi @DodoTrip the reason is that with inline CSS you can't define styles with states (eg. `:hover`) and media queries, so I've always seen it as a useless limitation instead of a feature. Despite that, you can still use that option if you don't need your components to be responsive or to have different states.

**Comment by DodoTrip** [comment]
Mind giving me  an example on how it is done right now or should avoidInlineStyle make it work easily?

**Comment by artf** [comment]
Honestly, I've stopped using avoidInlineStyle a long time ago, but I guess it should work 😁

**Comment by ronaldohoch** [comment]
Didn't work :( Tested right now
