### ISSUE TITLE
BUG: JSON.stringify(this.editor.getComponents()) Error

### ISSUE THREAD

**Issue by mmotov** [artf/grapesjs#3325]
**Version:** 0.16.44

Hi there! I have remote storage for pages, and recently I faced an issue when saving page, `JSON.stringify(editor.getComponents())` started to throw error `Uncaught TypeError: e[M].getId is not a function`.

I investigated the already saved JSON representation of the page and found out that it fails on this part

```
[
  {
    "tagName": "form",
    "type": "form",
    "attributes": {
      "method": "POST",
      "id": "form-id"
    },
    "components": [],
    "__symbol": "if5s0j"
  }
]
```
I don't know what's the purpose of the `__symbol` key, but without it, everything works fine.
This issue occurs only on few pages, but I'm afraid that it might happen again on other pages.

**Comment by yucomds** [comment]
Same erro here ... do you have a solution?

**Comment by josfh2005** [comment]
The same problem here, if I preprocess the components an remove that attr the template works fine.

**Comment by artf** [comment]
Yeah unfortunately the previous version of grapesjs had a bug that created symbols involuntary. In the current version, the bug is fixed and symbols are disabled, but unfortunately, this still happens if you try to load a component with a saved symbol reference (created by the bug).
I'll add a patch for this issue in the next release, for now, I'd follow Josè's advice and remove all `__symbol` references before loading the editor.
