### ISSUE TITLE
Nearly half the packages specified have high risk vulnerabilities, all have some vulnerability.

### ISSUE THREAD

**Issue by AmtechInnovarch** [artf/grapesjs#3332]
After npm i we can see that the level of vulnerabilities is unacceptable.

added 646 packages from 383 contributors and audited 762 packages in 7.892s
found 724 vulnerabilities (353 low, 23 moderate, 348 high)
  run `npm audit fix` to fix them, or `npm audit` for details

I'm trying to fix the problem, at least locally. It will take a long time because every single specified package has a vulnerability.

**Comment by AmtechInnovarch** [comment]
This is why veteran coders with decades of experience disapprove of JS as a back-end language. Javascript is not intended to be a server side language, and these node packages create vulnerabilities that get servers hacked.

```
grapesjs$ npm audit fix

changed 1 package, and audited 2026 packages in 3s

# npm audit report

diff  <3.5.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1631
fix available via `npm audit fix --force`
Will install documentation@13.1.1, which is a breaking change
node_modules/diff
  disparity  <=2.0.0
  Depends on vulnerable versions of diff
  node_modules/disparity
    documentation  4.0.0-beta - 13.0.1
    Depends on vulnerable versions of disparity
    Depends on vulnerable versions of yargs
    node_modules/documentation

mem  <4.0.0
Denial of Service - https://npmjs.com/advisories/1084
fix available via `npm audit fix --force`
Will install documentation@13.1.1, which is a breaking change
node_modules/mem
  os-locale  2.0.0 - 3.0.0
  Depends on vulnerable versions of mem
  node_modules/os-locale
    yargs  4.0.0-alpha1 - 12.0.5 || 14.1.0 || 15.0.0 - 15.2.0
    Depends on vulnerable versions of os-locale
    Depends on vulnerable versions of yargs-parser
    node_modules/yargs
      documentation  4.0.0-beta - 13.0.1
      Depends on vulnerable versions of disparity
      Depends on vulnerable versions of yargs
      node_modules/documentation

yargs-parser  <=13.1.1 || 14.0.0 - 15.0.0 || 16.0.0 - 18.1.1
Prototype Pollution - https://npmjs.com/advisories/1500
fix available via `npm audit fix --force`
Will install documentation@13.1.1, which is a breaking change
node_modules/yargs-parser
  yargs  4.0.0-alpha1 - 12.0.5 || 14.1.0 || 15.0.0 - 15.2.0
  Depends on vulnerable versions of os-locale
  Depends on vulnerable versions of yargs-parser
  node_modules/yargs
    documentation  4.0.0-beta - 13.0.1
    Depends on vulnerable versions of disparity
    Depends on vulnerable versions of yargs
    node_modules/documentation

7 vulnerabilities (4 low, 3 high)
```
This is a serious security concern and should be addressed by the developer, or there should be adequate warning in the readme.md that discourages production use without fixing all these vulnerabilities.

Is there a way to only use the client side layer of GrapesJS? Can the developer please identify the client side files?

**Comment by KernelDeimos** [comment]
GrapesJS has a server-side layer?

**Comment by KernelDeimos** [comment]
> Javascript is not intended to be a server side language, and these node packages create vulnerabilities that get servers hacked.

Are you implying that Javascript is the only language where dependancies can introduce security vulnerabilities? If there's some trait of Javascript that makes these sort of vulnerabilities more likely you ought to specify this in your statement, otherwise what you're saying is just subjective nonsense.

**Comment by Ju99ernaut** [comment]
> GrapesJS has a server-side layer?

Grapesjs is a completely client-side framework.

**Comment by Andrew-Chen-Wang** [comment]
> This is why veteran coders with decades of experience disapprove of JS as a back-end language. Javascript is not intended to be a server side language, 

And yet because JS is designed to be event driven, it's got the fastest backend frameworks. 

> Is there a way to only use the client side layer of GrapesJS?

> 724 vulnerabilities (353 low, 23 moderate, 348 high)

Like what Ju99ernaut said, this is fully client side and can be delivered by a CDN like static files. If you want a client side vulnerability checker, don't use npm. Use a static analysis tool like the one given by GitHub.

<details>
<summary>wtf?</summary>
wtf lol JS is just a scripting language. What vulnerabilities are there in JS besides XSS -- that really only happen client side based on user output in browsers -- or SQL injection -- which is just you creating custom SQL statements and not escaping properly etc. etc.? Plus, Python is just some general purpose language, yet lots of organizations like Pinterest, Instagram, Uber, and Reddit use Django, Django, FastAPI, Pyramids + Pylons. Organizations like Twitter and Uber use ExpressJS, which alone has 50k stars and most JS frameworks outperform Django and Flask based on the design concept of JS which is event-driven.

Don't get me started on Java because that's just huge dev time that's absolutely not needed at this point in the dev world.
</details>

**Comment by artf** [comment]
honestly, this is what I get from the current dev
```sh
found 3 vulnerabilities (2 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
All related to dependencies of `documentation` library (used to create API .md files for documentation).
Anyway, as others already had mentioned, GrapesJS is a client-side framework, so keep in mind that vulnerabilities reported by npm are mainly in libraries required for the development, so it's not something you deploy in production.
