### ISSUE TITLE
How extend Rich Text Editor (RTE)

### ISSUE THREAD

**Issue by ArtDesignCreativeStudio** [artf/grapesjs#334]
artf, a try to extend Rich Text Editor (RTE) (not replace), but without any result.

Can you help me with example?

Thanks!

**Comment by artf** [comment]
Hi @ArtDesignCreativeStudio honestly, I didn't spend too much time on this, even because I was thinking to replace the built-in RTE with something more stable (eg. [pell](https://github.com/jaredreich/pell))  but if you want it anyway check for example this #226 or directly the source of the [module](https://github.com/artf/grapesjs/blob/dev/src/rich_text_editor/index.js)

**Comment by ArtDesignCreativeStudio** [comment]
Thanks!
