### ISSUE TITLE
BUG: Using imported HTML/CSS/JS into the editor shows outlines, but no content, JS Fiddle inside

### ISSUE THREAD

**Issue by AndyNormore** [artf/grapesjs#3434]
*You can get the version by typing `grapesjs.version` into the console*
YES: https://jsfiddle.net/75a9u1cf/2/

**What is the expected behavior?**
I am expecting to be able to edit the HTML and content in the editor

*Describe the bug **detailed***
The screen is simply white, I can see the shapes and drag elements, but the editor is just not displaying the content

HALF-SOLVED: https://jsfiddle.net/75a9u1cf/3/

**Comment by AndyNormore** [comment]
![image](https://user-images.githubusercontent.com/1661561/117187316-cc15ef80-ada9-11eb-922e-de033b92a7e8.png)

**Comment by AndyNormore** [comment]
SOLVED IT, found some stuff on Google:

https://jsfiddle.net/75a9u1cf/3/

**Comment by AndyNormore** [comment]
![image](https://user-images.githubusercontent.com/1661561/117189874-adfdbe80-adac-11eb-97d6-a8518197c2ac.png)

**Comment by AndyNormore** [comment]
@artf  Come and help me :D

**Comment by Ju99ernaut** [comment]
Some things to note, these usually won't cause errors since the editor is able to fix them however they can cause some unexpected behaviours:
* script tags will not work by default,  the editor will remove them, here's reference on how to use scripts within the editor https://grapesjs.com/docs/modules/Components-js.html
* It's best not to include any html, head or body tags, they might mess up the structure of your page but usually the editor just ignores and removes them.
* Also important to check and correct invalid html, for example some images have a `</a>`, usually the editor is also able to remove these.
* You may run into CORS issues for external static files

**Comment by AndyNormore** [comment]
Thanks all will try these suggestions!

**Comment by AndyNormore** [comment]
Are you able to examine the JSfiddle link? It's display the exact issue

**Comment by AndyNormore** [comment]
I'm not even using custom components to do this, just trying to get HTML working :/

**Comment by Ju99ernaut** [comment]
> Are you able to examine the JSfiddle link? It's display the exact issue

I've managed to inspect the JSFiddle and the reason the images are not visible is because their container has `opacity: 0`, which is why I'm assuming the javascript is responsible for turning the opacity to 1, but it can't do that if it loads before the html.

**Comment by AndyNormore** [comment]
This issue can be resolved. I simply switched out the HTML/JS application to flat HTML -- disabled all the stupid loading effects. I'll just have an external script when not in editor do fancy stuff. 

ALL HAIL GRAPEJS.
