### ISSUE TITLE
FEAT: Post the full complete demo code

### ISSUE THREAD

**Issue by alpha2k-io** [artf/grapesjs#3527]
Is it possible to post the full demo code from the getting started?

There are many small snippets that depend on each other.  It would be good to have these in a repo as separate branches so developers can see the expected final result.  In many cases there were some simple things skipped or location of the snippet in the wrong place... IE css order. 

This is a powerful editor but a very steep learning curve to customize to meet requirements.  

Thanks,
AJ

**Comment by anlumo** [comment]
Yes, the problem is that the demo defines its own plugin that then imports all other plugins. This makes trying to find out how to do stuff really hard, because you have to follow a lot of redirects across different repositories. It's also not how you would write your own application based on grapesjs.

The link to the master demo plugin is also not as easy to find as the demo page, it's [here](https://github.com/artf/grapesjs-preset-webpage).

**Comment by artf** [comment]
The final code of the getting started tutorial is actually [here](https://github.com/artf/grapesjs/blob/dev/docs/.vuepress/components/DemoTheme.vue) (and its grapesjs [config](https://github.com/artf/grapesjs/blob/8b423fdf093865a6bf55dc8285030ce99c111d6d/docs/.vuepress/components/demos/utils.js#L364)).

> Yes, the problem is that the demo defines its own plugin that then imports all other plugins

@anlumo Yeah actually current presets plugins were structured in that way, probably right now I'd rethink them with a more modular approach where the `preset` itself is mainly the UI of the editor and the rest could be extended with additional plugins (components, blocks, etc.). Unfortunately, right now I'm not able to find time to fix them (there are also old AF) but I'd appreciate some help.

**Comment by erpardeepjain** [comment]
@artf but How to run that file or config file as main file is in vue and base project is in React, can you point out how to make it run as shown in demo?
