### ISSUE TITLE
Customize editor by removing all pallets on right and top

### ISSUE THREAD

**Issue by manjunaras** [artf/grapesjs#357]
First up all thanks @artf for your wonderful stuff on GrapesJS,

We need to customize complete editor instead of integrating into our app and most important it should be developer friendly  in following ways ,

1. Reuse editor region for content creation or edition.
2. Remove complete CSS and redesign as per our branding themes
3. Overriding evenlisteners( e.g., preview, undo/redo,etc.,) from our application (Reinvent in angularjs frontend)

@artf You openion whether it can be possible for above list of points mentioned?

**Comment by arthuralmeidap** [comment]
Hi @manjunaras ,
  I'm not @artf but , as far I have been reading about GrapesJS, with it's API , everything you mentioned is possible.
  Take a look here: https://github.com/artf/grapesjs/wiki

**Comment by manjunaras** [comment]
Hi @arthuralmeidap , Thank you so much for your guidance. 

We already went through the link you shared, But never mentioned anywhere about get editor part by removing their own css with eventlistener.

Let me brief about our need in Grapesjs,

![new mockup 1](https://user-images.githubusercontent.com/22448665/31111227-14272e8a-a82a-11e7-9409-67235feb1cfd.png)

We need to extract/re-use grapesjs editor region highlighted in yellow color with blocks and RTE.

Most important above the editor region or header we have our custom buttons Preview/Mobile view(highlighted in red color) On-click, which should follow same functionality Grapesjs follows.

On left side, It shows available html templates which again highlighted in yellow color.

So, in /src folder we need to remove/disable unused folders  Grapesjs, editor, Block-manager, Device-manager  and re-build again using webpack to get new grapes.min.js

In /src folder, need to do alter following changes as per above mockup.
 
**Required folders:** for preview/mobile/block manger, RTE for editor

**Not-required folders**:** Remove or disable following folders Storage manger, Asset manager, etc.,

After remove or disable need to re-build src folder using webpack to get fresh grapesjs.min.js

**Comment by arthuralmeidap** [comment]
Hi @manjunaras ,
  For css, GrapesJS provides some Sass variables that you can override and change some colors. Here you can check the available sass variables: https://github.com/artf/grapesjs/blob/dev/src/styles/scss/_gjs_variables.scss

  Starting from this [API-Editor](https://github.com/artf/grapesjs/wiki/API-Editor) you can start to save some templates ( from Submit button) 

 Using the same API you can implement a way to load the template from the templates palletes.
 Preview mode, should be a little bit harder to achieve but is pretty possible too.

  Are you having perfomance issues with GrapesJS ? Why do you want to remove some modules and others not? If you don't use, you can leave them there without problems but if you **really** need a new grapesjs without some folders, you can clone the code from github and remove what you want.

  Hope I could help

**Comment by artf** [comment]
Thanks @arthuralmeidap for a good overview.
@manjunaras I'd just add that buttons inside default panels (that you can actually hide) are executing [built-in commands](https://github.com/artf/grapesjs/blob/dev/src/commands/index.js#L88), so, for example, if you want to open the modal with HTML code just use `runCommand`:
```js
editor.runCommand('export-template')
```

**Comment by thecodefish** [comment]
@manjunaras @artf Hi I thought I'd throw in my own comment here as it sounds like your request is pretty similar to what I've built. I've got a 'report builder' built with AngularJs that uses GrapesJs to handle the actual html editing and it's working pretty well. We use our own code to handle the template management and just pass content/components back and forth to the grapesjs editor. We load the editor within a container so that we can tweak the CSS for the canvas, and using a combination of CSS and a plugin (which interacts with the various managers) we've hidden the grape components that we don't need.

I added a gist which you could maybe use as a starting point - it's an angular directive that will load a grapesjs editor (or more than one if you need) and it lets you hook into the grapesjs events and handle them within your Angular code. Note that it's using TypeScript. https://gist.github.com/thecodefish/d5680a5e6842fcc91f006714eb647106

It's probably not in a state where you can just copy it and go - it will most likely require some customisation (I stripped a bunch of our own custom stuff out of it and haven't really tested).

For preview mode what we do is retrieve the html from the editor (`editor.getHtml()`) and the css, inject it into the page into a preview container, hide the editor, and show the container - all through AngularJs.

Also I haven't modified the GrapesJs source at all. We're either working with what GrapesJs provides by default, we've turned things off (or hidden it), or we've overridden the commands/buttons to call back into our own code.

Hope this helps a little.

**Comment by artf** [comment]
Thanks @thecodefish good to know you were able to tweak GrapesJS and fit your needs 👍

**Comment by manjunaras** [comment]
@thecodefish: First up all i thank you from my heart for showing interest on my requirement and surprised we both sync together on same expectation on angular+grapesjs together and what exactly we also looking for. I gone through your pseudo angular code on integration using typescript. Its really good!!

Now, our requirement more relevant on binding JSON data and HTML template separate coming from controller through angular scope. So, once template and json rendered in grapesjs editor any modification in text/data should auto-update in same scope variable i.e., jsonData so that i can save it in database future.

For example,
------------------------------------------------------
class MyController {
  editor: any;
 grapesJsConfig: {
    //whatever
 }
**jsonData: {"title": "This is my sample title"}**
.....

}
<div ng-controller="myController as ctrl">
	<grape-editor id="whatever" config="ctrl.grapesJsConfig" **data="ctrl.jsonData"**></grape-editor>
</div>
------------------------------------------------------

class GrapesJsComponent implements ng.IComponentOptions
{
	bindings = {
		config: '<',
		id: '@',
               **data:'<'**
	}
        controller = GrapesJsController;
	controllerAs = 'editor';
        template = `<div id="gjs-{{editor.id}}"><div class="x" ng-model="data.title"></div></div>`;
}

angular.module('angularApp').component('grapeEditor', new GrapesJsComponent());


Please help us on above use-case and if possible can you share your complete pseudo set of source files. We are trying hard for a month.

**Comment by thecodefish** [comment]
The way that I've done that (handled passing data back and forth) is not to go via the directive, but rather to get a reference to the editor and then use the editor API directly.

For example, in my gist above, in `MyController` I have a reference to the editor object. I can call things like `editor.getHtml()` or `editor.setComponents(html)`. For example, this is my code to set up a new report:

``` ts
createBlankReport()
{
	var template = '<h1 reporttitle="1">New Report</h1><div>Report Description</div>';
	this.editor.setComponents(template);
}
```

And if I want to replace the content with an existing report, for example, I have code like this:
``` ts
this.editor.CssComposer.getAll().reset();
this.editors.setComponents(components); //components is a JSON object in my case - not html
this.editors.setStyle(css);
```

I also already have an event handler in my gist which detects when content is changed - you could combine that with a call to `editor.getHtml()` (or whatever you need) if you wanted to keep a copy of the html up to date. Personally I only get the html when it's needed, like when saving, I don't bother keeping it up to date all the time.
