### ISSUE TITLE
BUG: "/" in classes changing to "-"

### ISSUE THREAD

**Issue by simxn1** [artf/grapesjs#3623]
**Version:** ^0.17.19

**Are you able to reproduce the bug from the demo?**

 - [x] Yes
 - [ ] No

**What is the expected behavior?**
I would expect the class to stay exactly the same as I name it.

*Describe the bug **detailed***

When you add a class that contains a slash "/" character in it , in the DOM, it changes the slash character to a dash "-". 

*Describe the bug **detailed***
<img width="387" alt="Snímka obrazovky 2021-07-15 o 12 01 57" src="https://user-images.githubusercontent.com/75263268/125770945-6e83a6f8-d212-420c-968c-659f7c59941a.png">
<img width="823" alt="Snímka obrazovky 2021-07-15 o 12 02 02" src="https://user-images.githubusercontent.com/75263268/125770947-973bc9de-d515-4b7f-b47a-8b815b69d17d.png">

**Are you able to attach a screenshot?**

 - [x] Yes
 - [ ] No

**Comment by notauserx** [comment]
I also faced the same problem. After looing into the source, I found this is due to 

[https://github.com/artf/grapesjs/blob/8b423fdf093865a6bf55dc8285030ce99c111d6d/src/selector_manager/model/Selector.js#L123](url)

Based on [https://github.com/artf/grapesjs/blob/8b423fdf093865a6bf55dc8285030ce99c111d6d/src/selector_manager/config/config.js#L15](url)

I added the following option to fix my issue

`
var editor = grapesjs.init({
    selectorManager: {
	escapeName: name => name
    },
    // other options 
)
`
However, I do not know the motivation behind  the escapeName method in selector.js 
[https://github.com/artf/grapesjs/blob/8b423fdf093865a6bf55dc8285030ce99c111d6d/src/selector_manager/model/Selector.js#L118](url)
