### ISSUE TITLE
BUG: mousePosFetcher in resizer config & change:style listener not working

### ISSUE THREAD

**Issue by Joshmamroud** [artf/grapesjs#4097]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Brave V1.34.81

### Reproducible demo link

https://jsfiddle.net/joshmamroud/vkrcxuzb/41/

### Describe the bug

**How to reproduce the bug?**
1. Add a Grid block to the canvas
2. Resize a column
3. Notice the console logs aren't displaying for mousePosFetcher & this.listenTo(this, 'change:style', ...)

**What is the expected behavior?**
CBs should be called when mousePosFetcher is called
CBs should be called when "change:style" is called from this.listenTo(this, 'change:style', this.updateWidth)

**What is the current behavior?**
Callbacks aren't being triggered

I'm not sure why this is happening (or rather not happening) but it is extremely frustrating. I've read through the documentation and can't find any reason why this shouldn't work. Would really appreciate some help, @artf 

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @Joshmamroud 
> CBs should be called when mousePosFetcher is called

That is not happening because `resizable` options are not directly passed to the Resizer, but through the [`resize` command](https://github.com/artf/grapesjs/blob/dev/src/commands/view/Resize.js). You can see mousePosFetcher there is handled by the canvas. I can update the command in order to allow that kind of customization but keep in mind that the canvas does a bit more of your logic in order to get proper coordinates. For now, you can extend the command logic by yourself.

> CBs should be called when "change:style" is called from this.listenTo(this, 'change:style', this.updateWidth)

That is not happening because, in this case, the style is not updated on the Component itself, but on the [CssRule](https://grapesjs.com/docs/api/css_rule.html). Here is an example of how you would handle the listener by relying on the global event
```js
init() {
  console.log('Init Column')
  this.listenTo(this.em, `styleable:change:${keyWidth}`, this.updateWidth)
},
updateWidth(rule) {
  const ruleComponent = rule.getComponent?.();
  if (ruleComponent === this) {
    console.log('update width', rule.getStyle(keyWidth))
  }
},
```

**Comment by Joshmamroud** [comment]
Thanks @artf! That makes sense.
