### ISSUE TITLE
BUG: 0.18.3 text editing not triggering for link > text components

### ISSUE THREAD

**Issue by lofcz** [artf/grapesjs#4145]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 99

### Reproducible demo link

https://codesandbox.io/s/distracted-archimedes-fhmnpg

### Describe the bug

**How to reproduce the bug?**
1. open the demo
2. double click "I am text" component.

**What is the current behavior?**
Double clicking text elements (`span`, `i`...) inside `a` switches focus to the parent `a` element instead of opening rte for the selected element. This works correctly in 0.18.2.

From the template here https://codesandbox.io/s/1r0w2pk1vl minimal reproduction is to patch` index.html` from

```js
<div id="gjs">
 <div style="padding: 25px">Hello World!!!</div>
</div>
```

to

```html
<div id="gjs">
  <div style="padding: 25px">
    <ul>
      <li>
        <a href="#">
          <i>I am icon</i> <-- rte doesn't work on these two elements in 0.18.3
          <span>I am text</span> <-- rte doesn't work on these two elements in 0.18.3
        </a>
      </li>
    </ul>
  </div>
</div>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah, I see the problem. 

> Double clicking text elements (span, i...) inside a switches focus to the parent a element instead of opening rte for the selected element

With the [new logic](https://github.com/artf/grapesjs/blob/eb192dd914daf7c5af49deaa232db4dff6c8362d/src/dom_components/view/ComponentTextView.js#L28) implemented for the text components view, this is intentional. The idea was to prevent having nested RTEs by passing editing to the closest component with RTE.

Unfortunately, links have also [their own logic](https://github.com/artf/grapesjs/blob/eb192dd914daf7c5af49deaa232db4dff6c8362d/src/dom_components/model/ComponentLink.js#L34) applied during parsing in order to prevent RTE with links as blocks.
```js
<a href="...">
 <img .../>
 <h3>Block title</h3>
 <p>Block description</p>
</a>
```

I'll try to fix it, unfortunately, some opinions are necessary by default here, but at least you should always be able to suppress them by extending components.
