### ISSUE TITLE
BUG: Background modification doesn't work for non-images

### ISSUE THREAD

**Issue by DavidHarvey** [artf/grapesjs#4257]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v100

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Click any component, scroll to Decorations > Background in the style manager
2. Attempt to create a background with a basic color or gradient

**What is the expected behavior?**
I should be able to set a background with a color or gradient (in addition to image).

**What is the current behavior?**
I am only able to select an image for the background.

![image](https://user-images.githubusercontent.com/3315834/163210124-fe42c4ee-c436-4654-826c-0c82f017a5fe.png)
(Note that clicking on the color-picker looking area in the top right does nothing)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vac1911** [comment]
You can use the background color input for an image color but the UI looks confusing.
![image](https://user-images.githubusercontent.com/45333542/163394189-d3a12494-5194-40f7-a2f6-5c23d7702e70.png)

**Comment by artf** [comment]
Yeah, I disabled the previous plugin with color/gradients as it's not compatible with the latest versions but I'll work on it soon. For now, I close this issue as it has nothing to do with the core itself.

**Comment by bit-ocean** [comment]
Hi @artf
Is there a chance that this feature could get some attention? I find it fundamental. There is a lot of great functionality added to grapesjs since 0.17.29, the last one grapesjs-style-bg plugin supports) and I would love to use the new versions of grapesjs. It's great functionality offering easy work with layers of gradients, colors and transparency of images is crucial to me and holds back from upgrading. Thank you so much for your consideration.
