### ISSUE TITLE
HTML Parser does not honor custom added component types

### ISSUE THREAD

**Issue by sebastianha** [artf/grapesjs#43]
I am currently trying to implement by own custom component type and it seems to me that the html parser does not honor custom component types with their isComponent method and therefore they are not recognized as components. Can you reproduce this?

**Comment by artf** [comment]
Hi @sebastianha thanks for the hint
I think I forgot to mention one important step in docs. In this scenario:
```html
<div id="gjs">
 ...
 <cutom-element></cutom-element>
 ...
</div>

<script>
 var editor = grapesjs.init({
      container : '#gjs',
      fromElement: true,
  });

  editor.DomComponents.addType('cutom-element-type', {...});
</script>
```
In the example above the editor will not get the new type from the HTML because the content is already parsed and appended, so it'll get it only with new components (eg. from Blocks)

Solution: turn off `autorender`
```html
<script>
 var editor = grapesjs.init({
      autorender: 0,
      container : '#gjs',
      fromElement: true,
  });

  editor.DomComponents.addType('cutom-element-type', {...});
  
  // after all new types
  editor.render();
</script>
```
Could you try and let me know? If it's not working please post some reproducible example.

**Comment by sebastianha** [comment]
That's it, thank you very much!
