### ISSUE TITLE
BUG: Style Manager don't update background when component is selected

### ISSUE THREAD

**Issue by ronaldohoch** [artf/grapesjs#4350]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Brave Browser V1.39.111

### Reproducible demo link

https://jsfiddle.net/e7oau8v6/

### Describe the bug

**How to reproduce the bug?**
1. Thow a column in canvas.
 ![image](https://user-images.githubusercontent.com/2287371/170560918-15d2df09-58d4-41ee-b3f8-3313950b1669.png)

2. Select the text component
3. Go to style tab and find background on decorations
4. Set a background image.
![image](https://user-images.githubusercontent.com/2287371/170561020-99a64396-0ed5-4517-8f0a-8cce33061dd4.png)
5. Change the component.
![image](https://user-images.githubusercontent.com/2287371/170561085-00ceb031-8c54-4002-bfbb-d1408a091d3c.png)
6. The background property doesn't change
![image](https://user-images.githubusercontent.com/2287371/170561221-5243c156-2333-4146-ba6d-b8024c9aba1e.png)

**What is the expected behavior?**
That the background property update to current status of the component selected

**What is the current behavior?**
Background property don't update and keep the previous state, event if we trigger this: `editor.trigger('component:toggled');`

If is necessary to execute some code in order to reproduce the bug, paste it here below:
From line 9 to end of file of reproducible demo.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tuongnguyendev** [comment]
Hi @artf , I have a problem quite similar to @ronaldohoch when use the latest version of **GrapesJS**

**Background image preview** show error link

Details are in the image below:

![Screen Shot 2022-06-01 at 15 49 03](https://user-images.githubusercontent.com/16423468/171366767-be2677e7-d1b7-4fc7-ac45-7c54737dd41a.png)

**Comment by artf** [comment]
Hi @ronaldohoch the issue here is with your custom type background and the way you're adding it is not correct ([proper usage of the API](https://grapesjs.com/docs/modules/Style-manager.html#adding-new-types)). 
The `addType` is mainly for adding new UI inputs, if you don't need a new type of UI (like in your case) you can rely on [`addBuiltIn`](https://grapesjs.com/docs/api/style_manager.html#addbuiltin) to extend the default background properties (you can refer to [grapesjs-style-filter](https://github.com/artf/grapesjs-style-filter/blob/master/src/index.js) for a more advanced usage of `addBuiltIn`)

@tuongnguyendev your issue seems unrelated, please create a new issue with a reproducible demo.
