### ISSUE TITLE
Insert Text at cursor position inside text

### ISSUE THREAD

**Issue by sarathksasi** [artf/grapesjs#492]
Hi,

We are evaluating GrapesJS for one of requirement. As part of the evaluation i am creating custom command 'insert placeholder', what it does is ( what i am planning to do ) is when a select Text and when i click this command , it should insert text at the selected cursor position.

Initially i had done this 

   var existingData = selectedComponent.view.el.firstChild.data;
           
          var placeHolderData = '[[1# PlaceHolder Name]]';
          existingData = existingData + " "+placeHolderData;

            console.log("existingData ",existingData); 
        
          selectedComponent.set('content', existingData);

this is only appending text.  My requirement is insert at given cursor position. It will be great anybody can quickly come up with a solution for this ?

Thanks in Advance
Sarath K S

**Comment by mathieuk** [comment]
Duplicate with #481

**Comment by sarathksasi** [comment]
Thanks

**Comment by edwardjiawei** [comment]
Similar to what I did in [grapesjs-plugin-customrte](https://github.com/edwardjiawei/grapesjs-plugin-customrte/tree/master/src/main.js). But I no propose my code to be based on, at it is mess.

Also can set lower priority for implement _el.contentEditable_, 
so that the placeholder text is not editable. [#287](https://github.com/artf/grapesjs/issues/287)

Final, thanks for the good freedom work for artf. There is a lot of priority in grapesjs, maybe can shift to community plugin (artf/api-richtexteditor-plugin), maybe artf can decide to initiate the repo for [#481](https://github.com/artf/grapesjs/issues/481). So we can contribute when we see fit.
