### ISSUE TITLE
Asset manager delete problems 

### ISSUE THREAD

**Issue by duskhacker** [artf/grapesjs#549]
In the Asset Manager, when the `x` to remove an asset is clicked, it appears to fire both the `onDelete` event AND the `onClick` event. This puts the asset you just deleted into the target. Furthermore, one cannot click another asset to replace it in the target until you close the asset manager window and re-open it. 

If the user is not very careful, they can get the document into an inconsistent state that will not load properly from the server. 

Any pointers on how to fix this are welcome.

**Comment by ryandeba** [comment]
Hi @duskhacker,

I was able to recreate the issue of the onClick event firing when clicking on the `X` (jsfiddle in case anyone else cares to see it: https://jsfiddle.net/8v946q4b/3/). Sorry I don't have a lot of time to debug this myself at the moment (I may have time to research this tomorrow if you're still having trouble), but it appears to me to be a bug that should get fixed in the AssetImageView object. I see the `onRemove` method starts by calling `e.stopPropagation()`, which I believe is attempting to prevent the onClick method from firing, but that doesn't appear to be working if that is indeed the intent. My guess is that onClick is firing before onRemove for some reason, but I'm not sure this is the case nor why that would be happening.

**Comment by duskhacker** [comment]
> I may have time to research this tomorrow if you're still having trouble

@ryandeba Thanks for the followup! This is one of my outstanding problems with GrapesJS. I know I'm not going to be able to fix it in a reasonable time-frame, I'm not familiar with the code-base enough to debug effectively so I'll have to rely on your expertise. Currently, it is not a show-stopper I have lots of stuff to do before this goes into production. But if it can be fixed in the coming days that would be great!

**Comment by ryandeba** [comment]
@duskhacker - I've submitted a pull request that should fix this bug

**Comment by artf** [comment]
Merged, HUUUGE thanks Ryan :1st_place_medal:

**Comment by duskhacker** [comment]
@ryandeba: Thank you!! 💯

**Comment by ryandeba** [comment]
No problem! I'm happy to help out
