### ISSUE TITLE
import content dynamically

### ISSUE THREAD

**Issue by suraj740** [artf/grapesjs#571]
Hi @artf  , how can i import content dynamically  from program that automatically reflect in canvas.

**Comment by duskhacker** [comment]
In my project, I set `data-` attributes on an HTML element and extract them via `.dataset` in Javascript, once the editor is configured, I run: 

```
editor.setComponents(dataSet.legacyHtml);
editor.setStyle(dataSet.legacyCss);
editor.store();
```

Be aware that the HTML must be set up so that grapesjs can understand it. I believe that it must adhere to the BEM(http://getbem.com/) standard. In practice, I just created a few documents to understand what it's supposed to look like. 

Also, it doesn't matter where you get the HTML/CSS, it could be a remote call or just embedded in the Javascript, I just mentioned what I was doing as an example. 

HTH

**Comment by duskhacker** [comment]
@suraj740 ^^

**Comment by suraj740** [comment]
@duskhacker thanks , but i have to edit newsletter so i want to import it dynamically and also i am getting html with inline css getting from remote call. The thing is that i want to call that import function programatically not just by clicking on import button.

**Comment by duskhacker** [comment]
@suraj740 `editor.setComponents()` will take both html/css, so you could just skip the `setStyle` call. As for the rest, you did look at the storage manager documentation, yes? You can call `load/store` on it programmatically without clicking a button, like `editor.store(); editor.load()`

**Comment by duskhacker** [comment]
@suraj740 https://github.com/artf/grapesjs/wiki/API-Storage-Manager

**Comment by suraj740** [comment]
@duskhacker Thanks a lot bro :), its working now.
