### ISSUE TITLE
Scrolling issues when using the editor for partial editing

### ISSUE THREAD

**Issue by sebastianha** [artf/grapesjs#69]
So far your editor works really great, thank you very much for the hard work!

Currently I am trying to use the editor to let the users edit only a part of a page, e.g. a DIV,see here https://omoco.sofaecke.org/upload/20170413141840_screenshot1.jpg

As long as the editor is not larger than the page it works fine. But the outer window has scrollbars all the positioning and offset information of the editor are wrong, see https://omoco.sofaecke.org/upload/20170413141848_screenshot2.jpg

You see that the component is not at the cursor image and also the green placement line is wrong.

Would it be possible to adapt the editor that it can handle offsets when scrolling the window? That would be really great. I already tried for myself but without luck.

**Comment by artf** [comment]
Hi @sebastianha, yeah seems like it doesn't take care of the window scroll, will try to fix it. 
Anyway, for the moment, could you just try to fill all outer window height with the editor:
```js
var editor  = grapesjs.init({
  ...
  height: '100%',
})
```

**Comment by sebastianha** [comment]
Hi, the problem is, that – depending on the CMS template – I also have sites with a large header image, so I definitely have to scroll to get to the editing area. It would be very cool if you could take a look at it. Thank you very much!

**Comment by vankyy26** [comment]
In my case the % didn't worked that's why i used view height. May help someone.

`var editor  = grapesjs.init({
  ...
  height: '100vh',
})`

**Comment by artf** [comment]
Hi @sebastianha the last release (v0.5.40) should fix the issue, can you confirm?

**Comment by vankyy26** [comment]
I don't know did @sebastianha confirmed but it's fixed which is great! Only 1 think I'm thinking for. Right now when I use the editor on my 15,9-inch laptop the editor cannot fit inside the view screen. When I scroll down and pick a block from these at the bottom isn't possible to put it on a place while dragging because the window won't auto scroll above. So is it possible to auto move/scroll the page while dragging? Otherwise, i must put the block at the bottom and then move it to the desired place after manual scroll. I'm using the touchpad - no mouse. :)
![2017-06-03](https://cloud.githubusercontent.com/assets/10697327/26744846/656cff8a-47f0-11e7-8847-8e30e892ca27.png)
