### ISSUE TITLE
Suggestions - css background-size, DOM editor control, breakpoints

### ISSUE THREAD

**Issue by pingram3541** [artf/grapesjs#7]
Would love to see this or add it myself.  Maybe a quick fast track on on how to add new styling elements?  I'd like to add a select field for background-size, define the options array (cover, contain, custom -> being a conditional set of inputs for w/h/px/%/center/top...etc).

Also, if the code and css was editable too, that would make this pretty amazing.  It's pretty easy to make the codemirror objects update the DOM and even execute new scripts.  Emmet.io is another thing that comes to mind.  Rapid development from the editors, refinement and real-time testing with the gui.

````
var js_editor = $('#js-editor .CodeMirror')[0].CodeMirror;

js_editor.on('change', function(cm, change){
            //update content after 2 seconds            
            $('#js-editor iframe').contents().find('#custom-js').remove(); //needed to execute new js
            
            delay(function(){
                //update the DOM preview from editor contents
                $('#js-editor iframe').contents().find('body').append('<script type="text/javascript" id="#custom-js">'+cm.getValue()+'</script>');
            }, 2000);
        });
````

I also have some ideas for enhancing the breakpoints.

**Comment by artf** [comment]
Hi @pingram3541 thanks for all your suggestions. I apologize for the lack of documentation, hope to find some free time to write it. 
Anyway at the moment you're able to add new styling elements via configuration and I suggest you to look at the demo code for better understanding, so you'll see something like this:

```js
var gjs  = new GrapesJS({
...
styleManager : {
  sectors: [{
    name: 'SECTOR-NAME',
    properties:[{
              name: 'PROPERTY-NAME',
              property: 'CSS-PROPERTY',
              type: 'TYPE',   // Options: integer | radio | select | color | file | composite | stack
              ....
    }]
  }]
}
...
 });
```
About breakpoints, I've already thought how to implement their management but before I need something to manage components classes. In effect, if you look at the generated CSS you'll see there is no classes but only ids and it's no good at all. So with a 'ClassManager' will be easy to add 'BreakpointManager'

What about editable code viewer, it's possible but it's hard. Each component of the canvas has a lot of meta-informations (eg. removable, movable, stylable) that you lose after code generation so I see it as an unidirectional operation.

**Comment by pingram3541** [comment]
Thanks, this perfectly explains how to add new styling elements also visible in demo.js.

Where I'm hung up is in that the background-size property must be an option available within the background "stack" (due to multiple backgrounds being allowed per element), we would need to be able to control the background-size of each background added to the stack, however it appears the stack only deals with producing a single inline property and the way background-size is introduced via shorthand is incompatible with inline styling (i.e. background-position / background-size, the / is not allowed).  However, being able to add a separate background-size rule would suffice just fine.

Is there a way to to add a background-size property within the background stack but have it produce its own css attribute vs adding to the inline background property which doesn't allow the / notation?

**Comment by artf** [comment]
@pingram3541 glad you get some much stuff even without docs :D
Anyway I have tried this solution and it worked
```js
...
{
  name:     'Position Y',
  property:   'background-position',
  type:     'select',
  defaults:   'top',
  list:   [ { value : 'top',    name : 'Top', },
              { value : 'center',   name : 'Center', },
              { value : 'bottom',   name : 'Bottom', }],
},{
  name:     'slash',
  property:   'slash',
  type:     'select',
  defaults:   '/',
  list:   [{ value : '/', name : '/', }],
},{
  name:     'Size',
  property:   'background-size',
  type:     'select',
  defaults:   'auto',
  list:   [{ value : 'cover', name : 'Cover', },
           { value : 'contain', name : 'Contain', }],
},{
  name:     'Attach',
  property:   'background-attachment',
  type:     'select',
  defaults:   'scroll',
  list:   [{ value : 'scroll', name : 'Scroll', },
           { value : 'fixed', name : 'Fixed', },
           { value : 'local', name : 'Local', }],
}
...
```
You can eventually hide 'slash' property with CSS

Of course this is only the workaround. Unfortunately there is a lot of issue in compatibility with background shorthand (I've also tried to add background color inside stack but it works only for the first layer). 
The final solution will be to add some kind of property to 'stack' types for decide to render style from this:
```css
background: layer1, layer2, layer3 ...
```
to:
```css
background-prop1: layer1, layer2, layer3 ...
background-prop2: layer1, layer2, layer3 ...
background-prop3: layer1, layer2, layer3 ...
```

**Comment by nikadotme** [comment]
I don't like this script only, and I tell you why. this script maybe used into existing template editing, or something like that. 90% people who uses template editing they just edit existing one, but to make templates for this is not so easy, I mean you can't just download something from themeforest and parse simple HTML document. you have to build it first on Javascript, maybe I didn't read everything fully into codes, but everything that I see inside demo.js, it builds entire HTML document from JavaScript. and? how people will make templates? who will use it? no one. just some of them. I appreciate how good it is made, but when you do so big thing, you have to first think what will be useful for real people, why someone will use this script, if 10 template creation for this may take same amount of time, everyone will make their own. 

See the Ckeditor, I think ck is lot better, why? because you can parse html directly, without coding anything, and what is the idea here? program that needs tons of time to remake template for it? 

I don't know, I'd never used this. I know it's much like builder thing than ckEditor, but again, doing something and doing something but useful, are two different way of doing something.

sorry, but I was looking drag n drop builder for landing pages, to save time I tried to use opensource, but i decided to not use it. because I have to waste same time writing new editor myself, instead of making JSON based templates. 

if, I'm wrong... tell me why I am.

**Comment by artf** [comment]
Hi @nikadotme , I'm not sure why did you reply here, it might be better open a new issue.

Unfortunately, I see that you didn't get the true value of GrapesJS but I don't blame you, it's my fault for not providing a good documentation.
> I mean you can't just download something from themeforest and parse simple HTML document. you have to build it first on Javascript, maybe I didn't read everything fully into codes, but everything that I see inside demo.js, it builds entire HTML document from JavaScript

Yeah, you're right, the whole template is made up by a single JSON object, but there is a reason of this choice. At first, I've not yet implemented the HTML/CSS parser and then, it simply faster to load.

> how people will make templates? who will use it?

When you build templates inside GrapesJS you're able not only to export them but also to store the structure, for example, inside some DB. It's not yet documented but basically I'll show how to store HTML/CSS (front-end) and JSON (back-end), so let's see the JSON part as some kind of GrapesJS's file/extension to save your template projects.

> See the Ckeditor...

Ok, I agree with you about the HTML parser, but let's be honest, it's not fair comparing CKEditor vs GrapesJS. I would like to see you building something similar to GrapesJS's demo inside CKEditor, without coding...

> sorry, but I was looking drag n drop builder for landing pages, to save time I tried to use opensource, but i decided to not use it. because I have to waste same time writing new editor myself, instead of making JSON based templates.

I'm not sure what you're looking for. The demo [here](http://grapesjs.com/demo.html) it's not GrapesJS, but it's what you're able to achieve with it. The demo shows you some kind of 'website builder' but it's not the main purpose, you could also make some newsletter or webapp builder.
So if you're looking a tool for building website pages you should check some other well-known SAAS solution, otherwise I suggest you to try [Silex](http://www.silex.me/) which is completely free HTML builder and you're able to make stuff in few minutes.

For any other question open another issue, please

**Comment by artf** [comment]
Hi @pingram3541 I've added 'detached' property for the 'stack' type. So it's now possible to change the output from this:
```
css-prop: layer1, layer2, layer3 ...
```
to:
```
css-prop1: layer1-1, layer2-1, layer3-1 ...
css-prop2: layer1-2, layer2-2, layer3-2 ...
css-prop3: layer1-3, layer2-3, layer3-3 ...
```

For example with a background property:

```js
...
{
  name    : 'Background',
   property  : 'background',
   type    : 'stack',
   preview   : true,
   detached: true, // <- default is false
   properties  : [{
        name: 'Image',
        property:   'background-image',
        type:     'file',
        defaults:   'none',
      },{
         name:     'Repeat',
         property:   'background-repeat',
         ....
      }, {
          name: 'Position',
          ....
      },
      ...
}
...
```
