### ISSUE TITLE
Two devices with same width

### ISSUE THREAD

**Issue by kevinalvarez** [artf/grapesjs#727]
Hi all,
We have an scenario where we need to have two devices with same width. Almost everything works fine, but when we try to change between these devices (same width), the elements from the preview don't answer until we change another device with different size.

Any idea?

Thanks!

**Comment by artf** [comment]
What do you mean with `the elements from the preview don't answer`?

**Comment by kevinalvarez** [comment]
I can't edit the elements, like "read only"

**Comment by artf** [comment]
@kevinalvarez can't reproduce. Can you create a live demo?

**Comment by kevinalvarez** [comment]
Look at this demo: https://jsfiddle.net/9w2g8su5/1/
I have 4 devices. General and Desktop have the same width. If I change from General to Desktop (or vice versa), I can't select or edit any component from the canvas until select another device with different width

**Comment by ryandeba** [comment]
Hi all,

I did a little bit of research into this, I believe the issue starts inside of `FrameView.updateDim()` when `em.stopDefault()` is called, which stops `select-comp` (the default command) until the resizing transition is done. Since the dimensions haven't changed, there is no resize transition, `FrameView.updateOffset()` never runs so the `select-comp` command is never started again. In code, [this](https://github.com/artf/grapesjs/blob/0153fb3120c3050deab31381808a1de9e211db01/src/canvas/view/FrameView.js#L33) runs, then [this](https://github.com/artf/grapesjs/blob/d6ffecf27633bc27632a173998222fea0c041b37/src/editor/model/Editor.js#L447) runs, and [this](https://github.com/artf/grapesjs/blob/0153fb3120c3050deab31381808a1de9e211db01/src/canvas/view/FrameView.js#L41) is expected to run after the transition ends but never does. I don't know what the fix is, but here's a [jsfiddle ](https://jsfiddle.net/246zsynx/1/) that replicates the issue after 2 seconds (see the setTimeout at the bottom) without messing with the devices at all.

Is calling `em.stopDefault()` necessary inside `FrameView.updateDim()`? I'm guessing there's a good reason for it, but I'm not sure what that reason is.

@kevinalvarez - here's a hacky fix if you need to a working solution right now: [jsfiddle](https://jsfiddle.net/9w2g8su5/3/)

**Comment by kevinalvarez** [comment]
Thanks for the help, @ryandeba ! It worked fine with the code you sent. We can move on :). I hope there can be a fix inside the library.

**Comment by artf** [comment]
> Is calling em.stopDefault() necessary inside FrameView.updateDim()? I'm guessing there's a good reason for it, but I'm not sure what that reason is.

It's there to prevent fixed highlighting box which appears when you hover components during the animation 😬

I'll put a fix which will gonna check on the dimension change otherwise `udpateOffset` will be triggered immediately
