### ISSUE TITLE
Impossible to select Iframe

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#845]
I've created a new type of component an general iframe, avoiding selecting the map, but when I try to select it in canvas so that the settigns appear it's impossible for me.

This is the component code.

```
comps.addType('myiframe', {
        model: defaultModel.extend({
            defaults: Object.assign({}, defaultModel.prototype.defaults, {
                'custom-name': "IFRAME",
                tagName: 'iframe',
                src: "",
                traits: ['name', 'id', {
                    type: 'text',
                    label: 'src',
                    name: 'src',
                    changeProp: 1
                }],

            }),
        }, {
            isComponent(el) {
                var result = '';
                if (el.tagName == 'IFRAME' && /http/.test(el.src) && !/map/.test(el.src)) {
                    result = { type: 'myiframe', src: el.src };
                }
                return result;
            },
        }),
        view: defaultType.view,

    });
```

**Comment by artf** [comment]
Hey @chiqui3d try to copy the **view** logic from the [ComponentMapView](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentMapView.js). Basically you're not able to select it because everything inside it is overlapping the iframe element itself (elements inside iframe are out of the editor's scope).
As you see from the Map, basically you have to wrap the `iframe` inside a `div` and disable pointer events (via `gjs-no-pointer` class) otherwise the div will be overlapped too

**Comment by chiqui3d** [comment]
OK, but then I can never edit the previously created iframe src, or I can do is create a div envelope with editor on load in the view, for iframe elements not created from grapesjs. 

thanks @artf
