### ISSUE TITLE
[QUESTION] No spacing with new button in export window 

### ISSUE THREAD

**Issue by kewilson** [artf/grapesjs#855]
I've implemented a new plugin that adds another button in the export window, it's working fine. However when the page displays there isn't a space between it and the existing "Export ZIP" button.

How might I go about adding a space the grapesjs way? Is it just figuring out which html dom element properties to tweak? .. e.g., https://www.w3schools.com/jsref/dom_obj_all.asp

**Comment by kewilson** [comment]
ok so button.style.paddingLeft = "30px"; works but I've noticed that the border area where the buttons reside don't distinguish between the two .. i.e., no button border around each button's text. Because the Export ZIP button is not under our control how might we go about adding a button border around it and subsequently our own .. eg with round corners, etc. ?

**Comment by kewilson** [comment]
![buttons](https://user-images.githubusercontent.com/7303569/36038202-a6e8c214-0d84-11e8-8e41-741a1bad1394.PNG)

**Comment by kewilson** [comment]
notice in the image above that by setting my button's border it still encroaches on the zip button's space. would like to have the zip button have its own border with a space then our button with its own border so I can remove the paddingLeft .. any ideas how to go about that?

Do we need to somehow tweak the  editor.Modal.getContentEl() ?

**Comment by ryandeba** [comment]
Hi @kewilson,

If I'm understanding your issue correctly, I bet setting the left margin instead of left padding would work a lot better...is this [screenshot ](https://imgur.com/a/Fx1XL) close to what you're trying to accomplish? If so, you could replace your `button.style.paddingLeft = "30px"` code with `button.style.marginLeft = "10px"`. Or you could do this in css (create a custom css file and load it right after grapes.min.css): `.gjs-mdl-content .gjs-btn-prim + .gjs-btn-prim { margin-left: 10px; }`

**Comment by kewilson** [comment]
Hey @ryandeba that'll do .. I'll give it a whirl. Thanks!

**Comment by kewilson** [comment]
Hey @ryandeba .. I wish to add a border to the buttons. Mine is easy when I create it but that doesn't achieve the goal. So I'm trying to modify both mine and the existing one via the code below when I add my button to the screen but it no worky, thoughts on what I'm doing wrong here?

`//Add button inside export dialog
if (c.addReactJsButton) {
  editor.on("run:export-template", () => {
	
	editor.Modal.getContentEl().appendChild(button);
	
	let buttons = editor.Modal.getElementsByTagName("button") || {};

	for (b in buttons){
	  b.style.border = "3px solid black";
	}

	button.onclick = () => {
	  editor.runCommand(cmd);
	};
  });
}`

**Comment by ryandeba** [comment]
Hi @kewilson,

This is a bit difficult to work with without a live code example (like a jsfiddle demo), but I'm seeing a few issues:
- `let buttons = editor.Modal.getElementsByTagName("button") || {};`
  - This is probably throwing an error since `editor.Modal` is not a dom element, so `getElementsByTagName` is not a valid method. `editor.Modal.getContentEl().getElementsByTagName("button")` should work though.
  - Defaulting to an empty object here doesn't really make much sense.
- `for (b in buttons)`
  - I'm not very familiar with how to work with the `HTMLCollection` object returned by [getElementsByTagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName), but I suspect that iterating over it like this might not be valid. I'd recommend switching this to `querySelectorAll` as that will return an array (or at least an iterable object that closely resembles an array). 

Something like this might work:
```
let buttons = editor.Modal.getContentEl().querySelectorAll("button");

buttons.forEach(function(node) {
  node.style.border = "3px solid black";
});
```
