### ISSUE TITLE
"gjs-html' exceeded the quota

### ISSUE THREAD

**Issue by narraressan** [artf/grapesjs#87]
Hi guys, so I am making forms using this api and eventually my forms became too big - now the problem is when I load it it into the editor using editor.setComponents(components) it prompts this error. 

"Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'gjs-html' exceeded the quota."

Any ideas what I should do to load the forms? thanks ^_^

**Comment by artf** [comment]
Seems like you've reached the quota limit provided by the localStorage. There is no other way if not switch to another storage type. You can use the 'remote' one (already implemented [wiki](https://github.com/artf/grapesjs/wiki#storeload-data)), otherwise, another solution is to integrate [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB), which has no storage limits.

**Comment by tribulant** [comment]
Are you in Safari? I get this problem in Safari even if not in private browsing mode.

Best is to set the 

```
storageManager: {
type: ''
}
```

**Comment by artf** [comment]
@tribulant it's just due to the localStorage limit

**Comment by tommedema** [comment]
FYI it still happens when you disable storageManager's autoload

```
storageManager: { autoload: 0 }
```

is not sufficient, but this does disable it completely:

```
storageManager: { type: '', autoload: 0 }
```

**Comment by artf** [comment]
IndexedDB plugin https://github.com/artf/grapesjs-indexeddb
