### ISSUE TITLE
Is it possible to add a rich text editor (such as CKEditor) as a custom component?

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#93]
I tried it this way:

```
  blockManager.add('textarea-block', {
    label: 'Rich Text Editor',
    content: '<textarea></textarea>',
  });

  editor.on('component:add', function(model) {
    var el = model.view.el;
    if (el.tagName == 'TEXTAREA') {
      CKEDITOR.replace(el.id);
    }
  });

```

But the call to CKEDITOR above is throwing an error, indicating that the element with the specified id does not exist. I can verify that the id is correct if I inspect in Chrome, but document.getElementById() doesnt return anything. Am I missing something?

Thank you!

**Comment by artf** [comment]
Just use this :)
https://github.com/artf/grapesjs-plugin-ckeditor

**Comment by roytang** [comment]
Correct me if I'm wrong, but that plugin only changes the inline editor grapesjs uses for editing the contents of text elements yes? It's a bit different from what we want - we want to be able to add an actual <textarea> control with rich text editing features. Is this possible? Thank you!

**Comment by artf** [comment]
Ah ok, I didn't get what you meant.
I think CKEDITOR is throwing an error because there is actually no id in your component (`<textarea></textarea>`), but you can eventually pass the element itself:
```js
if (el.tagName == 'TEXTAREA') {
  CKEDITOR.replace(el);
}
```
Take in consideration that you RTE components will work only on add in GrapesJS, you need also somehow to init CKEDITOR once your pages are "in production". One of the solutions might be just to put textarea as a placeholder
```js
// in grapesjs
blockManager.add('textarea-block', {
    label: 'Rich Text Editor',
    content: '<textarea data-rte="1">This textarea will be replaced with CKEDITOR</textarea>',
  });

// production render page
$('[data-rte]').each(function() {
 CKEDITOR.replace(this);
});
```
